### ISSUE TITLE
[eBUG] Feedback plugin

### ISSUE THREAD

**Issue by Lidegand** [akasolace/HO#279] opened 2019-11-08 07:14 UTC
**Describe the bug**
I was trying feedback plugin and although I have same language in HO and HT (Catalan) it gives the following error:

"HT prediction ratings could not be parsed. Are you using HO either in English or in the same language as HT interface? If it is the case then please report the bug on GitHub."

It is probably due to different translations in HO and HT of what is copied, so as I am translator of Catalan, just need to know what are the labels used to parse rating prediction from Hattrick

**To Reproduce**
1. Go to Feedback plugin (after downloaded data with match orders being sent)
2. Paste Hattrick predictions in text box
3. Click on Update
4. See error (I see it in Catalan, just picked up English translation fro POEditor)

"HT prediction ratings could not be parsed. Are you using HO either in English or in the same language as HT interface? If it is the case then please report the bug on GitHub."

**Comment by mistermax80** [comment] 2019-11-08 10:49
@akasolace In order to make an other check on feedbackplugin, for english HT to check if the style of play is correctly parsed. I tried 100 offensive and its result it is ok, but I didn't check for defense.
Just an other check, I assume it works fine, but I have this doubt.

**Comment by akasolace** [comment] 2019-11-08 11:34
@mistermax80 we have time to look at this later on because for a while we will only request normal attitude. But let's try to keep this thread for the reported bug.
Do you have time to look at it with Catalan HT / Catalan HO ? Otherwise I will have a look this weekend

**Comment by mistermax80** [comment] 2019-11-08 11:36
@akasolace, ok, I think this nigth I will able to look it.

**Comment by mistermax80** [comment] 2019-11-08 23:34
@Lidegand 
The issue is:
ls.team.teamattitude --> current is 'Actitud'
but It has be --> 'Actitud de l'equip'
as you can see in the following:
`[table][tr][th]Defensa[/th][td align=center]2[/td][td align=center]1.75[/td][td align=center]2[/td][/tr][tr][th]Mig camp[/th][td colspan=3 align=center]0.75[/td][/tr][tr][th]Atac[/th][td align=center]0.75[/td][td align=center]0.75[/td][td align=center]0.75[/td][/tr][/table]
[b]Tàctiques[/b]: Normal
[b]Actitud de l'equip[/b]: Normal
[b]Estil de joc[/b]: 100% ofensiu`

**Comment by mistermax80** [comment] 2019-11-09 00:11
@akasolace my pr add an check: style of play has to be the same in HO and HT.
In this HT screen the user can modify (respect his coach) the style of play, lineup simulator:
![image](https://user-images.githubusercontent.com/15519907/68518754-ba738a80-028d-11ea-93de-39a8ee1afb51.png)
an example, I have the 100% offensive:
![image](https://user-images.githubusercontent.com/15519907/68518766-cbbc9700-028d-11ea-9806-852524ae655c.png)

**Comment by akasolace** [comment] 2019-11-10 12:10
closed by bfcdb08196cbea13a9a7231e76ac9e67141d978d

**Comment by mistermax80** [comment] 2019-11-10 15:26
@akasolace I would leave open this until the catalan lang has fixed.
@Lidegand could you give us confirmation on lang fix?

**Comment by akasolace** [comment] 2019-11-10 20:06
@mistermax80  you mean you are not sure your fix worked ? You did not try it for Catalan / Catalan ?

**Comment by mistermax80** [comment] 2019-11-10 20:21
Yes it works, but I didn't able to modify Che Catalan Lang, could you do it?

**Comment by akasolace** [comment] 2019-11-11 07:51
@mistermax80 yes I could change it but what should be done exactly ?
the language appears as 100% translated ...

**Comment by mistermax80** [comment] 2019-11-11 09:28
@akasolace read here https://github.com/akasolace/HO/issues/279#issuecomment-552031931

**Comment by akasolace** [comment] 2019-11-11 09:46
@mistermax80  ok I see "Actitud" ->  "Actitud de l'equip"
I will change that for Catlan. Should I also do this for Spanish ?

In parrallel, similarly to what was done for tactic, we can introduce partial match for attitude. Cause I am sure we will have similar issue n other language

   ```
 // language is not English and translation does not exist, we will try to parse using a proxy
        if (term == "ls.team.tactics") {
            String local_proxy_term = HOVerwaltung.instance().getLanguageString("ls.team.tactic").toLowerCase().substring(0, 5);
            String short_key;
            for (Map.Entry<String, String> entry : map.entrySet()) {
                short_key = entry.getKey().substring(0, 5);
                if (short_key.equals(local_proxy_term)) {
                    return entry.getValue();
                }
            }
        }
```

**Comment by mistermax80** [comment] 2019-11-11 11:36
Ok, I will do this, and push new PR, i think today.

**Comment by akasolace** [comment] 2019-11-11 13:10
@mistermax80 ok perfect

**Comment by mistermax80** [comment] 2019-11-11 14:48
@akasolace PR is ok.
But I find a new bug, could you check it and if it is confirmed open new one?
Situation:
HO lineup empty, the feedbackplugin doesn't recognize this different respect to the requirements, and you can send the feedback.

**Comment by akasolace** [comment] 2019-11-11 15:15
> But I find a new bug, could you check it and if it is confirmed open new one?
Situation:
HO lineup empty, the feedbackplugin doesn't recognize this different respect to the requirements, and you can send the feedback

Ok I will test test it, in the meantime I open a new bug ticket in order not to forget it.

**Comment by akasolace** [comment] 2019-11-11 15:18
once new artefacts are ready, I will let @Lidegand confirm the bug is closed

**Comment by Lidegand** [comment] 2019-11-11 15:37
I am very sorry that I did not check my email nor this thread since Friday. 

I can see that you fixed already for Catalan, I can check Spanish (just translation or also in HO)

**Comment by Lidegand** [comment] 2019-11-11 15:52
I have just checked Spanish (text from HT and in HO). Just to point out that there exists 3 different Spanish versions in HT and have different translations for ls.team.teamattitude.playitcool and ls.team.teamattitude.matchoftheseason

**Comment by Lidegand** [comment] 2019-11-11 15:53
> once new artefacts are ready, I will let @Lidegand confirm the bug is closed

Should I try to send feedback?

**Comment by akasolace** [comment] 2019-11-11 15:53
@Lidegand  similarly than for Catalan, you can check that for Spanish the term `ls.team.teamattitude` should be exaclty the same as the one you copy from HT rating (example below for Catalan as I do not have the one for Spanish:

`[table][tr][th]Defensa[/th][td align=center]2[/td][td align=center]1.75[/td][td align=center]2[/td][/tr][tr][th]Mig camp[/th][td colspan=3 align=center]0.75[/td][/tr][tr][th]Atac[/th][td align=center]0.75[/td][td align=center]0.75[/td][td align=center]0.75[/td][/tr][/table] [b]Tàctiques[/b]: Normal [b]Actitud de l'equip[/b]: Normal [b]Estil de joc[/b]: 100% ofensiu`

**Comment by Lidegand** [comment] 2019-11-12 07:20
Sorry, I did not explain myself properly. When I said "I have just checked Spanish (text from HT and in HO)." I wanted to mean that I changed ls.team.teamattitude so that it matches the one copied from HT, for example:

> [b]tikitakaboys - Atl. teleko[/b] [matchid=649186497]
> 
> [table][tr][th]Defensa[/th][td align=center]9[/td][td align=center]11.25[/td][td align=center]12.5[/td][/tr][tr][th]Mediocampo[/th][td colspan=3 align=center]11.75[/td][/tr][tr][th]Ataque[/th][td align=center]8[/td][td align=center]9.75[/td][td align=center]9.75[/td][/tr][/table]
> [b]Formación[/b]: 2-5-3 destacado (10)
> [b]Táctica[/b]: Normal
> [b]Actitud del equipo[/b]: Jugar relajados
> [b]Estilo de juego[/b]: Neutral

The next phrase was related to point out that even if you parse correctly ls.team.teamattitude, values from team attitude are different in different Spanish version in HT:

ls.team.teamattitude.playitcool
Español, España:   Jugar relajados
Español, Latinoamericano:  Jugar relajados (PIC)
Español, Rioplatense:  Jugar relajados 

ls.team.teamattitude.matchoftheseason
Español, España:   Partido de la temporada
Español, Latinoamericano:  Partido de la temporada (MOTS)
Español, Rioplatense:  ¡El partido de la temporada!

In Catalan I checked that both values in HT and HO matches for all 3 possibilities of team attitude

**Comment by Lidegand** [comment] 2019-11-12 07:29
> > once new artefacts are ready, I will let @Lidegand confirm the bug is closed
> 
> Should I try to send feedback?

Now it gives me another error, feedbackplugin.notMatchRequirements:

<p>Please check:</br><li>same lineup both in HO and in HT as required</li><li>same tactics both in HO and in HT as required</li><li>same attitude both in HO and in HT as required</li><li>same style of play both in HO and in HT</li></p>

Steps to reproduce the behavior:

1. Go to Feedback plugin (after downloaded data with match orders being sent). Note that I do not change players on Lineup page, I leave the ones picked by HO from HT
2. Paste Hattrick predictions in text box:
[b]Real HTZ - Atl. teleko[/b] [matchid=652265296]

[table][tr][th]Defensa[/th][td align=center]6.75[/td][td align=center]5.5[/td][td align=center]6.25[/td][/tr][tr][th]Mig camp[/th][td colspan=3 align=center]6.25[/td][/tr][tr][th]Atac[/th][td align=center]5[/td][td align=center]6.25[/td][td align=center]5[/td][/tr][/table]
[b]Sistema tàctic[/b]: 2-5-3 destacat (10)
[b]Tàctiques[/b]: Normal
[b]Actitud de l'equip[/b]: Normal
[b]Estil de joc[/b]: neutre

3. Click on Update
4. See error (I see it in Catalan, just picked up English translation fro POEditor)

I

**Comment by akasolace** [comment] 2019-11-12 07:52
> Please check same lineup both in HO and in HT as required
> Note that I do not change players on Lineup page, I leave the ones picked by HO from HT

@Lidegand I guess this is the error. The idea is to have the same lineup bot in HO and in HT otherwise we can't conclude anything on prediction rating. So currently HO require lineup with a single GK.  So in HO you should create lineup with just a GK (a single player on the lineup) and put normal attitude, normal tactic .... then you replice the same thing in HT (using the same player) and you copy the rating. You can check the deltas between HT and HO should not  be too big otherwise it might indicate something is wrong.

**Comment by Lidegand** [comment] 2019-11-12 11:33
I am sorry, I did not understand the explanation/graph. To be honest, I did not understand why you copied whole lineup positions as if it could be configured differently (it was shown all positions).

Now I understand it.

**Comment by Lidegand** [comment] 2019-11-12 11:38
Now it gives feedbackplugin.serverError error when clicking on Send (update worked ok):

[ho_token-BRIU9HYPW8] The data has not been successfully sent, server error. You can report this error by opening a new bug ticket on GitHub.

**Comment by akasolace** [comment] 2019-11-12 12:25
@mistermax80  can you check that token ho_token-BRIU9HYPW8]  on server and get extra information of what might have gone wrong ?

**Comment by Lidegand** [comment] 2019-11-12 12:27
I tried again later with another ho_token number, but I did not copy it (just few seconds/minutes after writing my message about [ho_token-BRIU9HYPW8]

**Comment by mistermax80** [comment] 2019-11-12 13:46
@Lidegand I think the sending is not arrived on the server, maybe connection error and I like to investigate on this.
Could you attach here your log file? The file with same day on error facing.

Thanks,
Massimo

**Comment by Lidegand** [comment] 2019-11-12 18:06
[HO-2019-11-12.log](https://github.com/akasolace/HO/files/3837542/HO-2019-11-12.log)
Here are the logs

**Comment by mistermax80** [comment] 2019-11-13 09:35
@Lidegand I saw your log, but I see and exception doesn't specified...
I would know, how you connect to internet.
Do you use an proxy?
was you connected to internet?

Do you use windows? Otherwise which is your SO?
Could you send me the output of the following command (in windows press windows button and r, after write cmd, in the black screen write the command)?
`nslookup hofeedback.000webhostapp.com`

Let me know, thanks so much, it is very important this test.

**Comment by Lidegand** [comment] 2019-11-13 09:53
I tried (and now I am too) at work. I have internet connection through Ethernet.

We have a router with different LAN subnets and also DNS server is inside our LAN network. We also have VPN to our cloud servers. I am not the IT guy, but more or less I know what we have (we are small company).

The result of the command is:

lookup hofeedback.000webhostapp.com
Servidor:  vpnserver.dcos.urbiotica.nexus2
Address:  192.168.30.99

*** vpnserver.dcos.urbiotica.nexus2 no encuentra hofeedback.000webhostapp.com: Non-existent domain

I can see that 192.168.30.99 is our main DNS server.

Changing DNS to google ones, I received two different responses:

Servidor:  dns.google
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
Nombre:  us-east-1.route-1.000webhost.awex.io
Address:  2a02:4780:dead:eb19::1
Aliases:  hofeedback.000webhostapp.com


Servidor:  dns.google
Address:  8.8.8.8

Respuesta no autoritativa:
Nombre:  us-east-1.route-1.000webhost.awex.io
Addresses:  2a02:4780:dead:3363::1
          145.14.144.77
Aliases:  hofeedback.000webhostapp.com

Repeating some more time, it always answer second one.

Finally, with Google DNS I tried again to use feedback plugin and it worked. No idea why our DNS does not find hofeedback.000webhostapp.com, is it a new domain?

I have sent some feedback deltas.

**Comment by mistermax80** [comment] 2019-11-13 10:05
ok I saw your feedback send, are about 15 sent.
The host name is not new, it is active since 6 six (minimum)... I don't know, I think your local DNS is not updated.

**Comment by Lidegand** [comment] 2019-11-13 10:41
Ok, I will check with IT guy and if we cannot update, I will switch to Google DNS to send feedback

**Comment by mistermax80** [comment] 2019-11-13 10:57
@Lidegand ok, let me know if you will resolve, we have not a static ip and we have to use the hostname in order to reach the server.

**Comment by mistermax80** [comment] 2019-11-13 11:01
@akasolace the exception is "java.net.UnknownHostException", and I didn't catch these specific in order to show an specif messagge, in fact the error message is generic, have we to show an specifc message? Now the details are only in logs.

**Comment by Lidegand** [comment] 2019-11-13 11:23
> @Lidegand ok, let me know if you will resolve, we have not a static ip and we have to use the hostname in order to reach the server.

@mistermax80  I don't know when I will check it, but for me it is obvious that it is a problem in my side, if with Google DNS works. I will try it at home this weekend if I can.

**Comment by mistermax80** [comment] 2019-11-13 11:35
> @mistermax80 I don't know when I will check it, but for me it is obvious that it is a problem in my side, if with Google DNS works. I will try it at home this weekend if I can.

Ok, let me know the test result at home (if you will can).

Thanks

**Comment by akasolace** [comment] 2019-11-13 11:37
ok so I read the message, it is not an HT bug, hence I close the issue.
Thank you @mistermax80 for investigating

**Closed by akasolace** 2019-11-13 11:37 UTC
Labels: reso: invalid, reso: won't fix
