### ISSUE TITLE
fails in running HO on macOS Sierra

### ISSUE THREAD

**Issue by mavino** [akasolace/HO#96] opened 2019-02-10 04:59 UTC
I download HO_1.436.2.1036 and when I try to open the HO java file I get this error:
```
 [Error]   ExceptionHandler: java.lang.NullPointerException
 [Error]   ExceptionHandler: core.HO.main(HO.java:206)
 [Error]   ExceptionHandler: HOLauncher.main(HOLauncher.java:28)
```
And the software does not open

**Comment by brokenelevator** [comment] 2019-02-10 10:36
@mavino are you starting with a db present or without? there was a bug in 1036 that prevents creating new database. it has been fixed with latest [DEV](https://github.com/akasolace/HO/releases/tag/dev). please try it out.

**Comment by akasolace** [comment] 2019-02-11 11:36
@mavino, if you are using MacOS, you should use the dedicated build, not the zip folder.

**Comment by mistermax80** [comment] 2019-02-17 08:44
@all
I tried the last 1.346, and It works.
There is not an bug...
I think we can close.

**Comment by mavino** [comment] 2019-02-17 17:36
> @mavino, if you are using MacOS, you should use the dedicated build, not the zip folder.

How do you build? There are instructions to build?

**Comment by mavino** [comment] 2019-02-17 17:37
> @ALL
> I tried the last 1.346, and It works.
> There is not an bug...
> I think we can close.

I don't know where to find 1.346, can you give me a link, please?

**Comment by mavino** [comment] 2019-02-17 17:39
> @mavino are you starting with a db present or without? there was a bug in 1036 that prevents creating new database. it has been fixed with latest [DEV](https://github.com/akasolace/HO/releases/tag/dev). please try it out.

I am starting without a db present...anyways I have tried your link (DEV) and I still get the same error

**Comment by mavino** [comment] 2019-02-17 18:04
> > @mavino are you starting with a db present or without? there was a bug in 1036 that prevents creating new database. it has been fixed with latest [DEV](https://github.com/akasolace/HO/releases/tag/dev). please try it out.
> 
> I am starting without a db present...anyways I have tried your link (DEV) and I still get the same error

Then I tried with a db present and still nothing working

**Comment by mistermax80** [comment] 2019-02-17 18:17
@mavino try this https://github.com/akasolace/HO/releases/download/1.436/HO_1.436.2.1072_macOS.zip

**Comment by mavino** [comment] 2019-02-17 18:22
> @mavino try this https://github.com/akasolace/HO/releases/download/1.436/HO_1.436.2.1072_macOS.zip

OK I downloaded it, unzipped and it appears the icon HO 2.
When I tried to open it it gives me still this error:
```
java.lang.NullPointerException
	at core.HO.main(HO.java:206)
	at HOLauncher.main(HOLauncher.java:28)
```

**Comment by akasolace** [comment] 2019-02-18 10:55
@brokenelevator it looks like the bug you closed with one of your latest commits. Was the commit also suppose to fix cases with corrupted db ?

@mavino I believe that you still have a db folder in your home directory. Do you have a lot of history?
Please copy it somewhere else and then remove all HO related files from your home/
In case, you can also update java.  After that launch again HO and it should works.

In order to get your old data back in HO I will wait for @brokenelevator inputs as he is most familiar with that issue.

**Comment by mistermax80** [comment] 2019-02-18 11:28
@mavino 

> OK I downloaded it, unzipped and it appears the icon HO 2.

The HO 2 appears when you decompress zip in folder where there is an other file HO.

I suggest to:
1 - backup DB in other folder
2 - follow the Akasolace instructions
3 - remove all HO instances in application folder
4 - Clean download folder
5 - download file and decompress it
6 - Reinstall HO

**Comment by brokenelevator** [comment] 2019-02-18 16:22
@akasolace I know it does, that is why I suggested trying out DEV. It seems like a related problem.

Could be MacOS related but @mistermax80 has no bug.

Moreover, @mavino has the bug with or without database. There should be no bug without database because it was fixed, and there should be no bug with database because there never was a bug with database.

So...it may require some digging. See after which build it fails and ponder changes or ponder the database looking for things broken. There should be some more traceback somewhere like terminal.

I would try with an older database, we need all the clues we can get.

@akasolace about the fix.... it was not supposed to fix corrupted databases because databases should not have gotten corrupted in the first place. It is something to think about, but still, new database should get created no problem and there is a problem.

I can take a look at the database if the latest instructions fail.

**Comment by mavino** [comment] 2019-02-18 16:50
thanks a lot for helping me...
I wanna be sure I am talking your language: when you say database I always mean my hrf file I got from my other HO instance I have on another computer (a Microsoft computer where HO is successfully installed, however I need to get rid of this computer)...other than that I tried all the instructions suggested above by @akasolace and @mistermax80 but still nothing

**Comment by brokenelevator** [comment] 2019-02-18 17:10
@mavino No problem :)
When we (at least I) say database we mean the 4 files in db folder called database (or zipped backups).
It may make a significant difference if you think we mean hrf files.

@mistermax80 are MacOS hrf's any different than Windows/Linux?

**Comment by mavino** [comment] 2019-02-18 17:20
OK my hrf is coming again form a windows machine, it contains all the information about my team. It is created every time I open HO on my windows machine and I connected to Hattrick to update my team on HO on windows. Thus, I got that hrf file and put it on my mac, believing it was the 'database' some of you asked me to start HO on my mac with and believing it would have got all my hattrick team backups from the last time I opened it on my windows machine to my mac...

@brokenelevator I don't have any idea of those 4 files in db folders, where are they? How do I get them?

**Comment by mavino** [comment] 2019-02-18 17:36
OK I tried something else and not sure if correct since I am not an expert on computer:
I downloaded cradle after I git clone your GitHub HO,
than I ran gradle (trying to build it, I guess?!?)..
I got this error
```
> Configure project :
zipping distribution

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/marianoavino/Downloads/HO-1.436/build.gradle' line: 542

* What went wrong:
A problem occurred evaluating root project 'HO-1.436'.
> Could not get unknown property 'POEDITOR_APIKEY' for object of type de.jansauer.poeditor.POEditorExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by brokenelevator** [comment] 2019-02-18 17:39
ok...I hope we understand each other correctly. HRF file contains a team snapshot, team information at current time. Database contains all the HRF's and more. For now I won't go into details of how does the team download/update process work.

Adding HRF to clean HO should work, depending on are the HRF's different on MacOS or not. The result would be one week worth of data in HO.

Can you tell me exactly what you do, step by step to get the error?
You have HO_1.436.2.1072_macOS.zip and a HRF from Windows machine. What do you do?

About the 4 files.
I have no knowledge of MacOS. However on the Windows machine you have...take a look at this.

HO folder: [https://i.imgur.com/tDWEfHe.png](https://i.imgur.com/tDWEfHe.png)
the first position is the 'db' folder I mentioned.
db folder: [https://i.imgur.com/GgKXaHK.png](https://i.imgur.com/GgKXaHK.png)
the first four are the database files (the 4 files)
the last one is those 4 files archived in a zip (automatic backup)

**Comment by brokenelevator** [comment] 2019-02-18 17:43
> OK I tried something else and not sure if correct since I am not an expert on computer:
> I downloaded gradle after I git clone your GitHub HO,
> than I ran gradle (trying to build it, I guess?!?)..
> I got this error
> 
> ```
> > Configure project :
> zipping distribution
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/marianoavino/Downloads/HO-1.436/build.gradle' line: 542
> 
> * What went wrong:
> A problem occurred evaluating root project 'HO-1.436'.
> > Could not get unknown property 'POEDITOR_APIKEY' for object of type de.jansauer.poeditor.POEditorExtension.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 0s
> ```

Well, you would have to slightly alter the build.gradle file for it to work. I could send you a custom one but I don't believe that it is gonna help. I mean it will help for building HO but not gonna solve your problem.

**Comment by mavino** [comment] 2019-02-18 17:50
> ok...I hope we understand each other correctly. HRF file contains a team snapshot, team information at current time. Database contains all the HRF's and more. For now I won't go into details of how does the team download/update process work.
> 
> Adding HRF to clean HO should work, depending on are the HRF's different on MacOS or not. The result would be one week worth of data in HO.
> 
> Can you tell me exactly what you do, step by step to get the error?
> You have HO_1.436.2.1072_macOS.zip and a HRF from Windows machine. What do you do?
> 
> About the 4 files.
> I have no knowledge of MacOS. However on the Windows machine you have...take a look at this.
> 
> HO folder: https://i.imgur.com/tDWEfHe.png
> the first position is the 'db' folder I mentioned.
> db folder: https://i.imgur.com/GgKXaHK.png
> the first four are the database files (the 4 files)
> the last one is those 4 files archived in a zip (automatic backup)

OK I decompress the file HO_1.436.2.1072_macOS.zip in my folder Downloads where I have also the file hrf (and nothing else related to HO).
Then in the same folder it appears the icon HO which I click,
then I get:
```
“HO” is an application downloaded from the Internet. Are you sure you want to open it?
```
I open it, and as soon as I do that I get this error (see screenshot):
<img width="968" alt="screen shot 2019-02-18 at 12 49 55 pm" src="https://user-images.githubusercontent.com/22825333/52968627-d17af100-337b-11e9-81f3-99ca0343208f.png">

**Comment by brokenelevator** [comment] 2019-02-18 17:59
OK....interesting. It looks like the bug I mentioned earlier which got fixed already...or not as it seems even though @mistermax80 does not have it.

Can you get database from Windows machine?
remove db folder from MacOS (in the HO folder) and replace it with db folder from Windows machine. then try running HO again.

**Comment by mavino** [comment] 2019-02-18 18:33
Nothing still the same problem...see screenshot of my folder called db where I put inside the HO.app (even when the HO.app is outside of that db folder I get the same error..,.
<img width="675" alt="screen shot 2019-02-18 at 1 26 55 pm" src="https://user-images.githubusercontent.com/22825333/52970342-7ea43800-3381-11e9-8fb8-e6982bc198b2.png">

Regarding to running it on a command line, I could but I am not sure how to do it,
I tried ./HO.app or java -jar HO.app but they do not work...

**Comment by mavino** [comment] 2019-02-18 18:39
OK I was able to open it from command line
```
open -a HO
```
and still same error, HO opens and right away shows the have error

**Comment by mistermax80** [comment] 2019-02-18 20:03
@mavino
After the unzip to have to move HO in application folder.
Could you share screenshot of:
Application list, home folder?

@brokenelvator I shared the hrfs between win Linux Mac OS and I had not issue... IMHO are identical.

**Comment by akasolace** [comment] 2019-02-18 20:03
@mavino

Let me start again.
1) in your home folder (look on google if you don’t know what this is) backup the dB folder (without the ho app that you copied into and that should not be there)
2) backup your hrf files
3) delete ho app (all the one installed as you might have couples by now)
4) delete all files related to ho in your home folder
5) delete all ho related files that you might have on your desktop or download folder (everything related to HO except the backup you made on first steps) 
6) upgrade Java
7)download app for Mac OS from stable or 1.436 (not dev)
8) launch HO (it should works !!)
9) download your team data

If you get there let me know and we will look at recover your old data (the ones you backed up)

**Comment by mavino** [comment] 2019-02-18 20:51
> @mavino
> After the unzip to have to move HO in application folder.
> Could you share screenshot of:
> Application list, home folder?
> 
> @brokenelvator I shared the hrfs between win Linux Mac OS and I had not issue... IMHO are identical.

I put in applications, db in home same error see screenshot
<img width="769" alt="screen shot 2019-02-18 at 3 49 52 pm" src="https://user-images.githubusercontent.com/22825333/52975833-034c8180-3395-11e9-815b-9b1fab5287e2.png">
<img width="768" alt="screen shot 2019-02-18 at 3 49 05 pm" src="https://user-images.githubusercontent.com/22825333/52975834-05aedb80-3395-11e9-868c-ff67fa8e0042.png">

**Comment by mavino** [comment] 2019-02-18 20:52
> @mavino
> 
> Let me start again.
> 
> 1. in your home folder (look on google if you don’t know what this is) backup the dB folder (without the ho app that you copied into and that should not be there)
> 2. backup your hrf files
> 3. delete ho app (all the one installed as you might have couples by now)
> 4. delete all files related to ho in your home folder
> 5. delete all ho related files that you might have on your desktop or download folder (everything related to HO except the backup you made on first steps)
> 6. upgrade Java
>    7)download app for Mac OS from stable or 1.436 (not dev)
> 7. launch HO (it should works !!)
> 8. download your team data
> 
> If you get there let me know and we will look at recover your old data (the ones you backed up)

I followed all your steps, except Java which is 8 in my system, still got the same error

**Comment by mistermax80** [comment] 2019-02-18 22:30
I would like to help... I think that you should install TeamViewer and give us the control of your Mac... I don't know how resolve the issue...

**Comment by mavino** [comment] 2019-02-19 03:15
@mistermax80 TeamViewer installed...let me know how to proceed...Thank you very much!

**Comment by mistermax80** [comment] 2019-02-19 09:20
@akasolace @brokenelevator

If you have other ideas ok, else I don't know which other tries mavino can do.
Let me how I proced

**Comment by brokenelevator** [comment] 2019-02-19 11:51
@mistermax80 regardless of any new ideas I think it would be better to go with TeamViewer. It will clear misunderstandings and hopefully solve the problem or at least give us some new leads.

**Comment by akasolace** [comment] 2019-02-19 15:08
@mistermax80  I also think TeamViewer is a good option

I still think something is not done correctly on mavino side.  Having teamviewer you will see what is going on ... I am curious to hear more about it.

**Comment by mavino** [comment] 2019-02-19 15:37
OK thank you all about this.
I reside in Canada (Eastern side) and the time I could be available to do this is around 6-9 pm eastern time (or more flexible in weekends). Please, let me know when is good for you.

**Comment by mistermax80** [comment] 2019-02-19 16:05
Hi all, and @mavino,

I think we could schedule on next weekend, you can refer to at Rome time, and I can say I preferer to do the tries on saturday 23Feb, more/less in night hours (00:00 - 02:00 italy time). what your time it will be? It will be ok for you?

Let me know.

**Comment by mavino** [comment] 2019-02-19 22:02
@mistermax80, I am afraid I might not make it around that time/date (sorry about it)...
precisely you are proposing between midnight and 2 am of Sunday, Feb 24 (the night of Saturday Feb 23).
Here in Canada is going to be around 6 and 8 pm of Saturday and I guess I might not be home. Do you have another day/time you can think of?
Thank you very much again.

**Comment by mistermax80** [comment] 2019-02-19 22:51
Ok no problem, can you suggest some slot suitable for you on next weekend?
You will specify  Canada time / Italian time.

**Comment by mavino** [comment] 2019-02-20 03:16
@mistermax80 thanks a lot again...
would it be possible for you between 2pm and 4pm either this coming Saturday or Sunday (Italian time)?
Cheers

**Comment by mistermax80** [comment] 2019-02-20 10:21
@mavino if you use Skype you can add me.
https://join.skype.com/invite/pZp8MKARRAuJ

**Comment by mistermax80** [comment] 2019-02-24 19:58
Hi all.
with Mavino I reinstalled the HO in mavino's Mac. I did an fresh install... And It's works.
The issue is facing if yuo use an db created in Windows.
For Mavino is ok close issue, he can use ho.
Must we guarantee the compatibility for reuse db created under other operative systems?
I don't know the impact.
Do you (Dev team) think about?

**Comment by brokenelevator** [comment] 2019-02-25 13:52
@mistermax80 
As I understand HO works now, installed fresh, with no history.
Does @mavino need history or is fine with fresh install?

> The issue is facing if yuo use an db created in Windows.

What happens when you use Windows database? The earlier mentioned error or something else?

> Must we guarantee the compatibility for reuse db created under other operative systems?

I guess it would be nice to have a cross platform database but until now I have not encountered the problem. About 18 months ago I moved to Linux and for some time I was using Windows and Linux interchangeably. There was no problem with using the same HO. It just worked.
I'll test if that is still true and you could confirm the issue with MacOS.

**Comment by mistermax80** [comment] 2019-02-25 14:03
@brokenelevator 

> Does @mavino need history or is fine with fresh install?

For @mavino, he tolk me, it's fine with fresh install.
So, I didn't analysis more.
As possible, I will do a test on Macos with my "windows" DB.

Share your test.

**Comment by brokenelevator** [comment] 2019-02-25 14:13
@mistermax80 If he is fine with it then OK :)

> As possible, I will do a test on Macos with my "windows" DB.

Do it both ways if you can :)

> Share your test result.

It works both ways. Databases created with 2 HRF added.

**Comment by mistermax80** [comment] 2019-02-25 16:26
I tried run HO on Win, with "Macos DB", It's works... but I notice (quickly) skill decimal lost and HO doesn't ricalulate the decimal.
I think that, in order to certificate the reuse the db in other different operative system, we should do more accurate tests.
As possibile, I will test (quickly) on Macos with my "windows" DB.

**Comment by brokenelevator** [comment] 2019-02-25 17:01
Interesting...
I redid the tests and Windows/Linux doesn't seem to have that problem. Decimals are present. Both ways.

As for `recalculate player skills`...something just dawned on me. HRF's are not enough for the recalculation. Relevant matches have to be downloaded. The function works.

**Comment by mistermax80** [comment] 2019-03-01 10:39
Hi @brokenelevator 
I confirm work also under macos with "windows db".
I think there was something wrong in old Mavino's DB.

I can we can close the issues.
I will use the same db for win and macos, if it will get out some error I will open a new bugs...

Let me know how you want go ahaed.

**Comment by brokenelevator** [comment] 2019-03-01 14:41
@mistermax80 So it works. I don't think there is a point in pondering Mavino database. Especially since we don't even have it.
I'll close the issue. Reopen if there is a need.

**Closed by brokenelevator** 2019-03-01 14:41 UTC

**Comment by mavino** [comment] 2019-03-01 15:42
Thank you very much for all the help...

**Comment by brokenelevator** [comment] 2019-03-02 14:31
You are very welcome :)
