### ISSUE TITLE
[eBUG]cup match missed in matchanalizer

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#313] opened 2019-12-09 23:49 UTC
When you have a other match in.week, as for eg battle match, in team analyzed we cannot see the cup match.

**Comment by akasolace** [comment] 2019-12-11 13:24
@mistermax80 I don't use matchanalyser. Is it a bug only when there is a battle match or also exist with friendly ....

**Comment by yaute74** [comment] 2019-12-11 20:52
@mistermax80  @akasolace  I do a modification recently for battle match in matchanalyser maybe it will work better with it

**Comment by akasolace** [comment] 2019-12-12 07:31
@mistermax80 can you please confirm whether or not the bug still exist ?

**Comment by mistermax80** [comment] 2019-12-12 08:23
@akasolace  I will check next Monday

**Comment by yaute74** [comment] 2019-12-12 19:31
@mistermax80 For info we could have the same id for an official match and a tournament match. Before my correction, for the battle match, it download the official (who have the same id) instead of the battle match.

**Comment by akasolace** [comment] 2019-12-14 16:16
@mistermax80  I just had a look and I am missing my division battle opponent. I don't know if it was always the case (missing non official game) or not

**Comment by mistermax80** [comment] 2019-12-14 19:07
For me official match it was missed

**Comment by mistermax80** [comment] 2019-12-17 14:12
Today situation:
HT:
![image](https://user-images.githubusercontent.com/15519907/71002459-9f433880-20df-11ea-9c56-366646c7af22.png)
last 2.0:
![image](https://user-images.githubusercontent.com/15519907/71002340-58554300-20df-11ea-9248-f1f3ba78c41e.png)
last dev code:
![image](https://user-images.githubusercontent.com/15519907/71002391-7d49b600-20df-11ea-8ed0-dde19b231136.png)

**Comment by akasolace** [comment] 2019-12-17 15:39
so with 2.0 you are missing secondary cup 
and with latest dev  you are missing both secondary cup and division battle but you got something else (Mori, which kind of game is that ?)
so looks like the bug is confirmed, now we have to decide, how many team we want to present here, own team + next 5 fives opponement ? 
do we want to include all kind of game (non official, ...)

**Comment by mistermax80** [comment] 2019-12-17 16:23
I don't know "I 4 Mori" nothing future match....

**Comment by yaute74** [comment] 2019-12-23 13:05
@mistermax80 it's a regression ? 
because if we look the source code for me it's "normal" to don't see the secondary cups.
for the battle, do you enable the checkbox 'Tournament Games' in dev version ? Because by default it's disable and me must scroll to see it.

**Comment by mistermax80** [comment] 2019-12-23 16:36
I will check it.
In addition I noticed if I see the match in the same match day, there are not visibile...

**Comment by mistermax80** [comment] 2019-12-24 10:29
today:
last code dev (by ide):
![image](https://user-images.githubusercontent.com/15519907/71408997-54c23e80-2640-11ea-83c8-9ff86b389e84.png)

last 2.0:
![image](https://user-images.githubusercontent.com/15519907/71409041-76bbc100-2640-11ea-8ae5-603183874323.png)

ht:
![image](https://user-images.githubusercontent.com/15519907/71409077-9521bc80-2640-11ea-8573-12d66c7aab98.png)

**Comment by yaute74** [comment] 2019-12-28 13:28
I have a battle match this week, so I reproduce, I will do a PR tonight

**Comment by akasolace** [comment] 2019-12-29 17:04
closed by fe94b0e79d63d844a527958e864b1c2405ebfb9f

**Closed** 2019-12-29 17:05 UTC
Labels: reso: info needed, type: bug
