### ISSUE TITLE
[eBug] Issue with TeamAnalyzer with Version 2.00 DEV (r1472)

### ISSUE THREAD

**Issue by Jeux12sl** [akasolace/HO#345] opened 2020-01-03 11:30 UTC
Using the above version, I don't succeed to download any match of my opponents in this module.
Clicking on the update button the application seems to perform download but in fact nothing appears in the list of match of my selected opponent.
If I downgrade to version 2.0 (build 1458) the functionnality works well.
I use the windows version of the application.

**Comment by wsbrenk** [comment] 2020-01-03 14:23
this behaviour i could reproduce with r1463 too.

workaround: push button "Analyse" after downloading.

**Comment by wsbrenk** [comment] 2020-01-03 14:27
even in HO 1.437 downloading did not show the matches list nor the rating panel. Only if you pushes "Analyse" these infos were displayed.

i do not know the behaviour of build 1458

**Comment by akasolace** [comment] 2020-01-03 14:31
@wsbrenk for what I can read on HO forum, pushing "Analyse" is not working. 
It seems that according to @Jeux12sl , the latest 2.1 build broke MatchAnalyser,  I havent tested it myself, ... 
to be confirmed.

**Comment by wsbrenk** [comment] 2020-01-03 15:02
@akasolace detached my git HEAD to 4be0e0a7349ff7823ef4c17955f4c2ee6e8df70d and the behaviour looks OK, but the debugger showed the following error;
Caused by: org.hsqldb.HsqlException: unexpected token: res.hattrick.org/tournamentlogo/29/285/2845/2844413/2844413.JPG, 2, 8, 2, 4, TIMESTAMP '2019-12-09 19:00:00', TIMESTAMP '2020-01-06 19:00:00', false, 2336787, Alexico)

do not know if running outside the debugger this could explain the described error?!

**Comment by wsbrenk** [comment] 2020-01-03 15:40
i could reproduce the error know if i select a tournament opponent. with tournament opponents the download does not work.

**Comment by wsbrenk** [comment] 2020-01-03 16:00
friendly worked on r1463 - division battle did not

**Comment by wsbrenk** [comment] 2020-01-03 17:21
could not reproduce this error with league match, because all my league matches were already stored in database.

**Comment by mistermax80** [comment] 2020-01-03 23:17
I confirm issue, and if your fix works, I will try in next days...

**Comment by akasolace** [comment] 2020-01-04 11:51
closed by b6bd67b

**Closed by akasolace** 2020-01-04 11:51 UTC
Labels: status: volunteer required, type: regression
