### ISSUE TITLE
[eFEAT] Players played or will play in week have a mark

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#231] opened 2019-09-28 22:37 UTC
Please refer to #44, https://github.com/akasolace/HO/issues/44#issuecomment-490609294

![image](https://user-images.githubusercontent.com/15519907/65823123-ca408d80-e250-11e9-9ff6-f8a339f7d7a0.png)
Following the previous implements, the idea is mark the player in different color if their played or will play a week end match or in week match (Hattrick does this).
Futhermore, in tooltip, we can show the minutes played or the estimated minutes.

**Comment by akasolace** [comment] 2019-09-30 09:21
@mistermax80  I think this is a duplicate of #125  (follow up of what @yaute74 did on the training view enhancement).  If you have something else in mind could you please clarify, otherwise I will let you close that issue.

**Comment by mistermax80** [comment] 2019-09-30 09:58
@akasolace ok, it is can see as enhancement respect to #125.
The idea can be to show an icon in player, this icon can be a matcht leageue, or other match, and obscured if the match doesn't played.

**Comment by akasolace** [comment] 2019-09-30 11:02
@mistermax80 currently with the color there are 4 information given: partial/full and past/upcoming 
The icon things could be nice but from what I understand we will only have the info about past/upcoming (we will loose the partial/full). Right ?

**Comment by mistermax80** [comment] 2019-09-30 11:17
Yes correct you said.

**Comment by yaute74** [comment] 2019-09-30 11:28
I think we can close because of #125

**Comment by mistermax80** [comment] 2019-09-30 12:21
Yes, we can close this, but I woulk like insert the match information (league or train match) with icon or test.
What do you think?

**Comment by akasolace** [comment] 2019-09-30 12:44
> Yes, we can close this, but I woulk like insert the match information (league or train match) with icon or test. What do you think?

Frankly, I am not sure that will be nice. Once stamina training is tracked, we can get between 22 and 28 trained players: 28 icons will be IMO very messy and much less informative than a cler color code.

**Comment by mistermax80** [comment] 2019-09-30 13:09
ok, i share your opinion

**Comment by akasolace** [comment] 2019-09-30 13:43
ok I close that one then ...

**Closed by akasolace** 2019-09-30 13:43 UTC
Labels: reso: duplicate, reso: info needed
