### ISSUE TITLE
Update Previsioni

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#221] opened 2019-09-24 08:43 UTC
HO throws exception, when I click on Calcola.
![Cattura](https://user-images.githubusercontent.com/15519907/65496078-1dfd5080-deb8-11e9-82b3-87b0341b8bf2.jpg)
log:
[HO-2019-09-24.log](https://github.com/akasolace/HO/files/3646168/HO-2019-09-24.log)

**Comment by akasolace** [comment] 2019-09-24 16:02
Also confirmed but  I am not sure that one should be supported anymore. I am not convinced it make any sense to introduce fixed correction by sector independently of other factors.  
I would suggest to remove that tab from the preference except if someone object.

**Comment by mistermax80** [comment] 2019-09-25 10:03
@akasolace I agree with you, but I suggest to remove "calcola" button and leave the tab.
Do you want remove for ever, or do you want remove for temporary? Can it use the function (if corrected)?

**Comment by akasolace** [comment] 2019-09-25 10:15
@mistermax80 I haven't look at it really but I guess it would be straightforward to fix that issue. However doing this, is in my view, a really bad idea. It might broke rating, it would also force us to adapt the plugin feedback ....

>Do you want remove for ever, or do you want remove for temporary? 
If we change our ming, with git we would simply have to undo the commit, so no big deal here really

**Comment by mistermax80** [comment] 2019-09-25 10:22
@akasolace Ok, remove it, but we should remember these funcion, in future can be useful (by update), my doubt is, if there is anypeople that has move the value, and we remove the tab, the prediction it will be wrong.

**Comment by akasolace** [comment] 2019-09-25 13:16
step 1: remove tab
step 2: remove offset from database remove offset from prediction ratings (alt. set offsets to 0 and dont touch prediction rating function)

**Comment by akasolace** [comment] 2019-09-27 13:04
feedback and test required before closing

**Comment by akasolace** [comment] 2019-09-27 16:09
@mistermax80  your commit looks fine to me !

**Closed** 2019-09-29 16:18 UTC
Labels: status: needs test, type: enhancement

**Comment by sirketzal** [comment] 2019-12-22 01:02
Why it has been removed? I found it useful tu recalculate the good puntuation that a position would have. Actually, I've one winger giving me 4.44 in the tab and in the game it had 6.00.

It would be available soon?

Thx.

**Comment by mistermax80** [comment] 2019-12-22 07:59
@sirketzal 
If you read prevoius comments you will nave the response.
If you have other doubts, you don't hesitate to aks US.

**Comment by sirketzal** [comment] 2019-12-22 11:40
> @sirketzal
> If you read prevoius comments you will nave the response.
> If you have other doubts, you don't hesitate to aks US.

@mistermax80 
First of all, I read all the topic before asking anything.
Simply, I asked if it will return because I played long time ago and with that functionallity HO! gave the exactly punctuation.

Anyway, thank you.

**Comment by mistermax80** [comment] 2019-12-22 11:49
I was not polemic, sorry for I gave you this sensation...
We have chosen to remove (temporary) that feature beacuse We don't know (in this moment)  if it works fine.
We introduced an new way to reach data player and rating in order to enhance the predictions.
When We gather enough data we release a new pretiction engine... You can see here https://github.com/akasolace/HO/wiki/FeedBack
I'm here for other explains...

**Comment by akasolace** [comment] 2019-12-23 11:31
@sirketzal we removed it because it was a dirty way to fix sector ratings.
We will focus in the near future in improving the ratings.

**Comment by sirketzal** [comment] 2019-12-27 23:26
> @sirketzal we removed it because it was a dirty way to fix sector ratings.
> We will focus in the near future in improving the ratings.

Perfect  @akasolace & @mistermax80, I appreciate your explanation and time.
Keep in touch. Good luck!

Kind regards.
