### ISSUE TITLE
[eBUG] coolness on IFA not display at HO start

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#72] opened 2019-01-09 21:01 UTC
**Describe the bug**
coolness on IFA tab is not saved on database.
It needs to be actualised every time.

**To Reproduce**
1. Go to 'IFA'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/50928016-b9997e80-1459-11e9-90eb-d04c3b6d5921.png)

**Platform information:**
 - Ubuntu 16.04

**Comment by akasolace** [comment] 2019-01-09 21:08
@DavidatorusF just for info, do you know i the bug present in 1.434 / 1.435?

**Comment by DavidatorusF** [comment] 2019-01-09 21:19
@akasolace 
1434 nice
1435 no... may be bug added when you updated this tool with the 5 new flags...

**Comment by brokenelevator** [comment] 2019-01-11 17:06
@akasolace @DavidatorusF `it's not a bug it's a feature` but jokes aside... there was a bug with ifa module that you fixed by executing `drop table` on `HT_WORLDDETAILS`. Now since we are using a non-stable version the database keeps updating on every run. So updating in ifa module fills the `HT_WORLDDETAILS` table but when we start HO again it's `drop table`**d**.
I checked, removing the `drop table` keeps the coolness.

Finally, either it will fix itself when we go stable (someone check that please) or there is something broken in DBUpdater. Meaning the database version does not increment for some reason.

**Comment by akasolace** [comment] 2019-01-11 21:09
@brokenelevator I confirm the bug was introduced recently, because on my local development version it was working well but not in the latest one.  I can also confirm that the issue is now fixed on the latest build.

@DavidatorusF  I let check on your side and if needed you can reopen the bug but to me it appears as fixed

**Closed** 2019-01-11 21:09 UTC
Labels: effort: unknown, type: bug
