### ISSUE TITLE
Improve usability team analyzer

### ISSUE THREAD

**Issue by ArneGloe** [akasolace/HO#66] opened 2019-01-01 18:09 UTC
Here is the issue as requested in the hattrick forum. Thanks for your work! Really appreciate it!

A great add on for me would be to save modified ratings of my next opponent. 
I often modify these according to my expectations while testing different line-ups in the team analyzer. Right now I manually reset them to my expectations every time I change the line-up.

**Comment by wsbrenk** [comment] 2020-05-02 15:16
![grafik](https://user-images.githubusercontent.com/11821502/80868037-3af0d200-8c98-11ea-91b7-63a97cd5cc42.png)

my idea is to add an extra row "adjusted" beneath the average row ("Durchschnitt"), when the user changes the opponents ratings in the MatchPredictionPanel. This row could be selected when user changes his lineup to simulate again with his adjusted match ratings.

**Comment by akasolace** [comment] 2020-05-02 15:52
@wsbrenk ok yes and how would the reset be done?
   - in the simulation we decide average or adjusted ?
   - in team analyser a button to reset adjusted to average ?
   - in team analyser a button to toggle adjusted row 
   - ...

**Comment by wsbrenk** [comment] 2020-05-03 00:08
@akasolace as long as the opponent team is not changed no reset is needed, i think.
if opponent team is changed the "adjusted" row will disappear, until the ratings of the new opponent team is adjusted. then the new adjusted ratings will be added to the list.

**Comment by akasolace** [comment] 2020-05-03 08:37
@wsbrenk ok sounds good !

**Comment by wsbrenk** [comment] 2020-05-30 16:02
progress report: it was a hard fight until i understood what is happening where. so i did a little refactoring of the code and i hope other developers confirms that it will get easier to understand. currently the ui looks like this - there is a new "adjusted" row after simulation was run with changed rating or tactic values.
![grafik](https://user-images.githubusercontent.com/11821502/83333148-6ff44280-a29f-11ea-9539-7c79faec8455.png)

currently i'm looking for the correct match type icon which should be copied from the adjusted match or empty - but not a wrong cup match icon.
And there is a lot of testing, which has to be done.

**Comment by akasolace** [comment] 2020-05-31 13:37
@wsbrenk I followed this one from far... but thank you for the status update !

**Comment by akasolace** [comment] 2020-06-08 08:14
might be implemented by ebc278f

@wsbrenk I will let you close the issue once tested and confirmed to work

**Comment by wsbrenk** [comment] 2020-06-08 17:38
@akasolace, @ArneGloe  we should try to get the author of the ticket for a test when a new dev version is in place

**Comment by wsbrenk** [comment] 2020-06-08 17:41
@akasolace i recognize that i worked longer than a month on this ticket - i'm really tired of this;-)

**Comment by ArneGloe** [comment] 2020-06-09 06:43
@wsbrenk: thanks for your work! Really appreciate it. 
I'm happy to test it as soon as I can. Do you want me to do anaything specific?
@akasolace: also to you thanks for your work. Fantastic to see how the project revived the good old HO.

**Comment by akasolace** [comment] 2020-06-09 07:15
thank @wsbrenk for the work, that was a big one !

@ArneGloe I will let you know as soon as we have new artefacts that you can test. We have made some heavy changes on the build system and it might take some time before we are back up and running ...

**Comment by akasolace** [comment] 2020-06-12 08:01
@ArneGloe  hello you can test using https://github.com/akasolace/HO/releases/tag/dev 
if you are on windows I suggest you to test using HO-4.0.0.2948-win-DEV-JRE.zip
In any case please recall it is a dev version and that you should backup your db.

**Comment by akasolace** [comment] 2020-06-12 08:07
@wsbrenk I made some test myself and it looks pretty neat !

**Comment by ArneGloe** [comment] 2020-06-12 12:22
I just downloaded the 4.0 version and played around a little bit.
@wsbrenk that's exactly what I have been looking for. Really cool feature. Thanks again
@akasolace I also played around with the rating prediction. With the new rating prediction type, team confidence has no effect on my attack ratings. There might be a problem. The prediction of the defense ratings improved a lot though.

**Comment by akasolace** [comment] 2020-06-12 17:23
@ArneGloe  thanks or the tests and the feedback .... I will check that

**Comment by akasolace** [comment] 2020-06-16 16:15
@ArneGloe this has been fixed(#570)

**Closed by akasolace** 2020-06-16 16:15 UTC
Labels: status: accepted/WIP, status: needs test, type: feature
