### ISSUE TITLE
[eBUG] Subskill recalculation not working

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#97] opened 2019-02-12 12:54 UTC
**Describe the bug**
I did lost the decimal skill

**To Reproduce**
- I downloaded the team data
- even by function subskill recalculation

**Screenshots**
![decimali](https://user-images.githubusercontent.com/15519907/52636684-9b49f700-2ecd-11e9-83a7-f1256bb90aaf.PNG)

**Platform information:**
 - OS: [Windows]
 - Version 1.436 last before 11/02

**Comment by akasolace** [comment] 2019-02-12 16:35
anyone else experiencing that issue?

**Comment by mistermax80** [comment] 2019-02-12 19:14
i sketched dB and I reimport all hefs... Now works... Could be something broken in dB...
@akasolace do you decide if you want close this issue

**Comment by akasolace** [comment] 2019-02-12 19:38
>> I sketched dB

What you mean by that? Any idea what could have cause the dB corruption in first place ?

I suggest to keep the bug open for a while in case other user are facing it. Would be surprise if you are the onl one ...

**Comment by mistermax80** [comment] 2019-02-12 19:44
😄 I removed DB.
I don't know, but I saved the db, we could analyze....

**Comment by akasolace** [comment] 2019-03-13 19:30
@mistermax80 should we close that issue or do you want to do some more digging first?

**Comment by mistermax80** [comment] 2019-03-15 09:56
I agree to close.

**Comment by akasolace** [comment] 2019-03-26 15:35
I am now having the same issue in my development branch ... I have lost all the decimals after file update.

**Comment by akasolace** [comment] 2019-05-02 21:16
I found that the problem for me was following upgrade 1.436 Beta -> 1.436 Stable the training date were not saved anymore in the database. I closed that bug with ef27789 .
However, subskill recalculation is still not working for me but I never tried it before. Does someone else experince the same bug ?

**Comment by akasolace** [comment] 2019-12-30 07:58
@mistermax80 @wsbrenk @yaute74 This should ideally be tackle for 2.1 but it is a big one so I suggest to leave it for 3.0 even if it is a bug and not a new feature. What do you think?

**Comment by yaute74** [comment] 2019-12-30 21:26
@akasolace I do a smal test and on my side and it works.

**Comment by wsbrenk** [comment] 2020-01-28 12:26
@akasolace as long as i was working on #199 i didn't see that bug.

**Comment by akasolace** [comment] 2020-01-28 12:51
@wsbrenk I just try it and I can't reproduce it anymore ...
I close this one

**Closed** 2020-01-28 12:52 UTC
Labels: reso: can't reproduce
