### ISSUE TITLE
[eFEAT] button "download match again" through Matches tab

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#181] opened 2019-07-27 13:55 UTC
**Is your feature request related to a problem? Please describe.**
In tab "Matches", we can download again a "corrupted" match but not a match without score (mean we missed to update HO during holidays or for an other reason)

**Describe the solution you'd like**
I want to be able to download the match again through the button bottom left without use module -> download matches (where I have to copy manually the matchid) or download matches since x times at start

kisscool effect: this feature can help for avoid wrong team for cup matches in team analyser

I know it can be not possible for tournament/ladder/single if they are nomore in HT archive, in this case, users will have to delete it

**Additional context**
![image](https://user-images.githubusercontent.com/45043004/61995170-e6735300-b084-11e9-93aa-d5c705c14a78.png)

**Comment by mistermax80** [comment] 2019-09-28 22:23
@DavidatorusF 
I tried to download old matches and it works fine.
Could you try? You should insert a past date respect missing matches.
![image](https://user-images.githubusercontent.com/15519907/65823044-2bfff800-e24f-11e9-970f-c56c13f052eb.png)

**Comment by DavidatorusF** [comment] 2019-09-29 18:03
@mistermax80 I know this solution work... but take time
it need to reload many matches not only the missing one

**Comment by mistermax80** [comment] 2019-09-29 20:31
Ok, When I will can I will see what I can do

**Comment by mistermax80** [comment] 2019-09-29 22:14
The issue is in the following table:
SELECT * FROM "PUBLIC"."MATCHESKURZINFO" a WHERE a.STATUS=2;
Match status is set to 2 for passed match. (status 2 = match doesn't played)

@akasolace do you have some ideas?

**Comment by akasolace** [comment] 2019-09-30 09:15
@mistermax80  I haven't looked into that issue and I don't know which part of the code you are referring to. Just to make sure we are aligned on what the issue is:
@DavidatorusF would like to be able to download match from matches tab (download game for the selected row). If I undestand correctly it is not possible to do so for games for which match details are not in the database. @DavidatorusF is that correct?  Also could you tell me in which scenario you need to download game for which match details are already present? Game details are corrupted? Any idea how this could happen? Any other reasons?

**Comment by mistermax80** [comment] 2019-09-30 12:26
>  If I undestand correctly it is not possible to do so for games for which match details are not in the database. @DavidatorusF is that correct?

Yes, past matches have not details in db their have status = 2 (match not played)
The solution shuld be that download match.
You can see this effect also in the following screen:
![image](https://user-images.githubusercontent.com/15519907/65878401-4e4c5f80-e38e-11e9-8fb7-91659f47c1d6.png)

**Comment by akasolace** [comment] 2019-09-30 12:48
@mistermax80  the example you are showing is for future game so here it is normal they have status 2 (match not played).
I am still wondering which kind of past games have no details in the db (I imagine it is game for which HRF were not downloaded, HO not used for more than a week for example). In that case we need to understand why HO does not offer to download match details of such game and to fix this.
I was also curious to understand whether or not a user could have an interest in redownloading match details (how could it be corrupted in the db) but it is a less important question. @mistermax80 , @DavidatorusF  are we aligned about the request ?

**Comment by mistermax80** [comment] 2019-09-30 13:07
@akasolace the match in my example refer to a match played in june, it is past.

**Comment by DavidatorusF** [comment] 2019-09-30 13:08
for add the missing match, we can
- reload since a date in the login
- use "modules -> teamanalyser -> download a match", then restart HO for see the match

the question is why the reload button don't work for missing matches as we have his matchid ?
![Capture du 2019-09-30 14-40-06](https://user-images.githubusercontent.com/45043004/65881591-eb5dc700-e393-11e9-8855-989be3e430da.png)

**Comment by mistermax80** [comment] 2019-09-30 13:10
These match have status = 2, but they have past.

**Comment by akasolace** [comment] 2019-09-30 13:44
> @akasolace the match in my example refer to a match played in june, it is past.   

Indeed I misread

**Comment by akasolace** [comment] 2019-09-30 13:46
>the question is why the reload button don't work for missing matches as we have his matchid at the end of the line in the table? 

The only reason I could imagine is a limitation from CHPP. Otherwise we should be able to provide a fix relativly easily.

**Comment by akasolace** [comment] 2019-09-30 13:50
> These match have status = 2, but they have past

I guess forward games come in db with that status. When match details are requested from main tab, the status is updated. Matches for which match details were not requested, do not get their status updated.
Hence I think the following fix could work:
   - option 1)    match tab, decided to activate/deactivate the download button not on match status but on playing date
   - option 2) match tab when a game is selected, check whether or not the match is played and update the status accordingly

@mistermax80 do you want to give it a try ?

**Comment by akasolace** [comment] 2019-09-30 13:59
@mistermax80 yes I think I see where the problem is coming from. Hence, what about my proposal just above? I think this is an easy quick fix, no?

**Comment by mistermax80** [comment] 2019-09-30 14:03
I would like go in option 1), but if you dont see issue on check date.

**Comment by akasolace** [comment] 2019-09-30 15:29
> I would like go in option 1)

ok great I assign it to you then

**Comment by akasolace** [comment] 2019-10-02 15:49
@mistermax80 have you started working on it already ? Otherwise I could give it a try tonight as I might find a bit of time, let me know ...

**Comment by mistermax80** [comment] 2019-10-02 16:01
@akasolace no I don't start...
You should insert check for date in 2 point:
1) in tab matches (@DavidatorusF screenshot https://github.com/akasolace/HO/issues/181#issuecomment-536552653)
2) in league details (@mistermax80 screenshot https://github.com/akasolace/HO/issues/181#issuecomment-536538055)

**Comment by akasolace** [comment] 2019-10-02 18:02
@mistermax80 ok I will have a look

**Comment by akasolace** [comment] 2019-10-02 18:42
@mistermax80 I fixed the one in tab matches but I could not reproduce the one in league details.
I will try to fix it next saturday after my league game. I open a dedicated ticket for this.

**Closed** 2019-10-02 18:45 UTC
Labels: type: enhancement
