### ISSUE TITLE
Error after moving to a new series

### ISSUE THREAD

**Issue by markdoub** [akasolace/HO#704] opened 2020-09-28 10:03 UTC
Hi, I get these errors every time I download my team data.
![err1](https://user-images.githubusercontent.com/16538045/94418919-f0598000-0179-11eb-970c-913dcb8bc635.png)
![err2](https://user-images.githubusercontent.com/16538045/94418930-f4859d80-0179-11eb-856b-1f40133b55db.png)

My team players are updated correctly. But the "League details" tab is empty.

I moved to a new series before the new season started. I think it started happening just after this.

 - OS: Linux
 - Version 3.0 (Build2728)

**Comment by akasolace** [comment] 2020-09-28 11:34
@markdoub  can you backup your db and test latest beta version ... this error should be gone.

**Comment by Angelus2005** [comment] 2020-09-28 14:33
Same error here.... i also moving to a new series but diffrent OS: WIN10 but same Version: 3.0 (Build2728)

**Comment by Angelus2005** [comment] 2020-09-28 14:46
latest beta also generate the same errors OS: win 10 version: 4.0 r3242 (Beta)
i don´t know why :/

**Comment by tychobrailleur** [comment] 2020-09-28 14:48
I have the same error here:

```
java.lang.RuntimeException: CHPP Error - 8748459 - Hattrick Archive
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:664)
	at core.net.MyConnector.getMatchLineup(MyConnector.java:292)
	at core.file.xml.ConvertXml2Hrf.createHrf(ConvertXml2Hrf.java:141)
	at core.net.OnlineWorker.getHrf(OnlineWorker.java:81)
```

I will investigate later, but looks to me like either a CHPP (breaking) change, or there are still some funnies on CHPP side.

**Comment by markdoub** [comment] 2020-09-28 18:52
I was ready to try v4.0 and thought I should try one more time with v3.0. It works! I didn't change anything (db or version)...
Could it be related to HT being down?
But my "League details" tab is still empty and it shows my old Series for season 61

**Comment by tychobrailleur** [comment] 2020-09-28 19:02
It is also working for me this evening on 4.0 – impossible to reproduce.  I suspect it was indeed funnies on CHPP that were fixed in the meantime.

**Comment by akasolace** [comment] 2020-09-29 08:00
I also tried and I could not reproduce it ... I am closing this one

**Closed by akasolace** 2020-09-29 08:00 UTC
