### ISSUE TITLE
[eBUG] Unable to Set Future Trainings

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#269] opened 2019-10-28 22:09 UTC
**Describe the bug**
On opening the the application for the first time, the future training was set to "Defending".
This meant the wrong players were shown to have received training.  On trying to change the "Future Training" I got an error report.

**To Reproduce**
1. Open "Training Tab"
2. Click on "Set All" (Future Training)
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/48737160/67721882-8a93cf80-f9cf-11e9-9a6b-918816f4f730.png)

**Platform information:**
 - Windows 10
 - v2.0

**Error Content**
setSelectedIndex -5 out of bounds
java.lang.IllegalArgumentException: setSelectedIndex: -5 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at module.training.ui.comp.FutureSettingPanel.jbInit(FutureSettingPanel.java:80)
	at module.training.ui.comp.FutureSettingPanel.<init>(FutureSettingPanel.java:46)
	at module.training.ui.TrainingPanel$1.actionPerformed(TrainingPanel.java:84)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mistermax80** [comment] 2019-10-28 22:39
The stamina training is raise to 10.
I think you had a 5, it's correct?

Could you download the new data (F11) and retry?

**Comment by mistermax80** [comment] 2019-10-28 23:11
@Synthespian 
In order to use the your current version you can run this command
`UPDATE "PUBLIC"."FUTURETRAINING" SET staminatrainingpart = 5 where season = 73 AND staminatrainingpart < 10`

You should insert in 'Debug' -> 'SQL Editor'
![image](https://user-images.githubusercontent.com/15519907/67724788-7e643e00-f9e0-11e9-8007-de3ec12bd669.png)
then press the gears icon.

Please, first, You must make a DB backup.

**Comment by akasolace** [comment] 2019-10-29 11:55
@mistermax80 your latest PR fixes it, right ? So maybe @Synthespian just have to wait for new artefacts ...

**Comment by akasolace** [comment] 2019-10-29 11:58
once, BETA 2 is out we will check the issue is fixed before closing it

**Comment by mistermax80** [comment] 2019-10-29 12:00
By PR the issue is closed, you can merge and release new artefacts.

**Comment by akasolace** [comment] 2019-10-29 12:14
closed by 56b372d5a7c543f72ab4b698422e8585d999bf2a

**Closed by akasolace** 2019-10-29 12:14 UTC
Labels: status: needs test
