### ISSUE TITLE
[BUG] HO! can't access internet. proxy ? Firewall ?

### ISSUE THREAD

**Issue by manfredberner** [akasolace/HO#840] opened 2021-01-01 17:39 UTC
[HO-2021-01-01.log](https://github.com/akasolace/HO/files/5759214/HO-2021-01-01.log)
Hello,

I get multiple errors with new HO 4.1 especially when I try to download team data. Find log below.

**Platform information:**
 - Windows 10

**Comment by akasolace** [comment] 2021-01-01 18:09
@manfredberner those are annoying but nothing wrong here.
@wsbrenk one of this day, lets clean up those verbose debug message

**Comment by wsbrenk** [comment] 2021-01-01 18:24
> one of this day, lets clean up those verbose debug message

@akasolace especially if they are declared as Errors. But to be honest, i didn't find the place, where the wrong position ids between scorer and bench positions were used.

**Comment by manfredberner** [comment] 2021-01-01 19:32
@akasolace thanks for quick reply. they are really annoying it takes some minutes for each update and I have to click on OK for each error message. I cannot download historical data as it would take hours me clicking on OK.

**Comment by manfredberner** [comment] 2021-01-01 19:33
[HO-2020-12-25.log](https://github.com/akasolace/HO/files/5759335/HO-2020-12-25.log)
 btw: some more errors I got the other day

**Comment by akasolace** [comment] 2021-01-01 19:35
> @akasolace thanks for quick reply. they are really annoying it takes some minutes for each update and I have to click on OK for each error message. I cannot download historical data as it would take hours me clicking on OK.

@manfredberner this is a different issue, not related to the logs you shared

**Comment by akasolace** [comment] 2021-01-01 19:36
> [HO-2020-12-25.log](https://github.com/akasolace/HO/files/5759335/HO-2020-12-25.log)
> btw: some more errors I got the other day

ok this log is shows you have an issue.  Is this happening all the time or only on some occasions?

**Comment by manfredberner** [comment] 2021-01-01 19:51
Each time I download

**Comment by akasolace** [comment] 2021-01-01 20:50
could you share your database?  if you can paste here a downlable link, I will have a look

**Comment by manfredberner** [comment] 2021-01-01 21:58
[db.zip](https://github.com/akasolace/HO/files/5759485/db.zip)

here it is. can you delete when you have it so not everyone sees it?

**Comment by akasolace** [comment] 2021-01-21 07:53
@manfredberner sorry I had no time to look at your issue so far. Before I dig into it, could you please test if you still experience this issue in latest 5.0 dev version.  Please backup your database before testing it.  If issue still exist I will start working on it.

**Comment by manfredberner** [comment] 2021-01-22 14:42
Where can I download 5.0 dev zip portable? When I update via HO itself it does not start after update :-/

**Comment by akasolace** [comment] 2021-01-22 14:46
https://github.com/akasolace/HO/releases/tag/dev

**Comment by manfredberner** [comment] 2021-01-22 14:57
thanks. I unzipped it to a new folder and when I start I get the following error: 

java.lang.NullPointerException: Cannot invoke "core.model.Team.getTeamSpirit()" because the return value of "core.model.HOModel.getTeam()" is null
	at module.lineup.LineupSettingsPanel.<init>(LineupSettingsPanel.java:103)
	at module.lineup.LineupRatingAssistantPanel.initComponents(LineupRatingAssistantPanel.java:36)
	at module.lineup.LineupRatingAssistantPanel.<init>(LineupRatingAssistantPanel.java:29)
	at module.lineup.LineupPanel.initComponents(LineupPanel.java:105)
	at module.lineup.LineupPanel.<init>(LineupPanel.java:37)
	at module.lineup.LineupMasterView.initComponents(LineupMasterView.java:51)
	at module.lineup.LineupMasterView.<init>(LineupMasterView.java:39)
	at module.lineup.LineupModule.createTabPanel(LineupModule.java:29)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:472)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:166)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:245)
	at core.HO.lambda$main$2(HO.java:199)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by akasolace** [comment] 2021-01-22 15:12
@manfredberner how do you obtain the error? You copy the database in HO! folder and then you launch the app, correct ?

**Comment by manfredberner** [comment] 2021-01-22 15:27
Downloaded zip (portable win with jre) and unzipped. Even deleted db to start fresh

**Comment by akasolace** [comment] 2021-01-22 15:37
so you have the crash even without a database ? just launching HO! ?

**Comment by manfredberner** [comment] 2021-01-22 15:40
Yes, removed db and user json to start from scratch

**Comment by akasolace** [comment] 2021-01-22 15:43
you are under windows ?

**Comment by manfredberner** [comment] 2021-01-22 15:45
Yes

**Comment by akasolace** [comment] 2021-01-22 15:52
I just opened a ticket for this:  #859

**Comment by akasolace** [comment] 2021-01-22 21:01
@manfredberner I fixed the issue that was causing the crash on fresh install. 
Please try now with latest DEV version (3389) and let me know if you still experience this issue. 
thank you

**Comment by manfredberner** [comment] 2021-01-23 11:00
Errors still occur with 5.0. First download took over 30 minutes due to multiple errors which needed an "OK" from my side. See log attached.
[HO-2021-01-23.log](https://github.com/akasolace/HO/files/5860061/HO-2021-01-23.log)

**Comment by wsbrenk** [comment] 2021-01-23 13:11
@akasolace initColumns of table AUFSTELLUNG doesn't init SOURCESYSTEM column

**Comment by akasolace** [comment] 2021-01-23 13:22
should be fixed by 688b4e43c973de6fd74120286a7e02297f8b9a95

**Comment by akasolace** [comment] 2021-01-23 13:23
@manfredberner I will soon release new dev version that you could test ....

**Comment by manfredberner** [comment] 2021-01-31 14:32
Unfortunately still lots of errors with HO-5.0.3392.0-portable-win-DEV-JRE. Log attached
[HO-2021-01-31.log](https://github.com/akasolace/HO/files/5899916/HO-2021-01-31.log)

**Comment by akasolace** [comment] 2021-01-31 14:37
@manfredberner you have this when launching fresh new install ?

**Comment by manfredberner** [comment] 2021-01-31 14:45
yes

**Comment by akasolace** [comment] 2021-01-31 16:02
ok I see the issue, I will fix this one shortly and let you know ...

**Comment by akasolace** [comment] 2021-01-31 20:01
@manfredberner actually I see now you have a connection error. Are you using HO! behind a proxy. Could it be that your firewall is blocking HO from accessing internet ?

**Comment by manfredberner** [comment] 2021-01-31 21:33
No firewall, proxy. With HO 3 all is good.

**Comment by akasolace** [comment] 2021-01-31 22:09
You have this error after you put the security code ?

**Comment by manfredberner** [comment] 2021-02-01 06:35
Yes

**Comment by akasolace** [comment] 2021-02-01 09:07
@manfredberner really I can't reproduce.
I just downloaded HO-5.0.3392.0-portable-win-DEV-JRE,  I launched it put my security code and I was good to go. 
The only thing that is different on my system is that I have Java 15.0.1 installed (https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jre_x86-32_windows_hotspot_15.0.2_7.msi).
In theory this should not be required but if you can give it a try and see if it solves your issue ....

**Comment by akasolace** [comment] 2021-02-01 09:17
@wsbrenk @tychobrailleur I just realized we are still using scribe 1.3.0 which has been release in 2011. Are we holding this one for any particular reason or should we try to bum the version see if it makes connection to HT more reliable .... (personally I never encountered issue but maybe latest version provide more information about connection time out issue). What do you think ?

**Comment by tychobrailleur** [comment] 2021-02-01 12:07
Yes, I remember upgrading, and then reverting again during the Java 11 upgrade – I believe this was because of Java modules issues, which we finally solved.

I can look into upgrading this lib again (it was working fine after the upgrade), but IMHO the issue at hand here is unrelated.

**Comment by manfredberner** [comment] 2021-02-01 12:16
I installed java 15.0.1 but that didn't help. To be clear: Security code works. But downloading works only with many, many errors.

**Comment by akasolace** [comment] 2021-02-01 12:33
>  Yes, I remember upgrading, and then reverting again during the Java 11 upgrade – I believe this was because of Java modules issues, which we finally solved.

@tychobrailleur I actually did the upgrade just after my last message as I recalled it was modules related. 

> I can look into upgrading this lib again (it was working fine after the upgrade), but IMHO the issue at hand here is unrelated.

Yes I also doubt it will help

**Comment by manfredberner** [comment] 2021-02-01 19:57
it finally worked with 3407. thank you

**Closed** 2021-02-02 16:47 UTC
Labels: reso: can't reproduce
