### ISSUE TITLE
Out Of Bounds Exception for Hall of Fame players

### ISSUE THREAD

**Issue by LEOSCHUMY** [akasolace/HO#350] opened 2020-01-10 19:08 UTC
Version 2.0
If I try to select an Hall of Fame players into Player Analysis (F5 menu), I got an error

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at core.gui.model.UserColumnFactory$6.getTableEntry(UserColumnFactory.java:148)
	at core.gui.model.PlayerAnalysisModel.initData(PlayerAnalysisModel.java:134)
	at core.gui.model.PlayerAnalysisModel.setValues(PlayerAnalysisModel.java:149)
	at module.playeranalysis.SpielerMatchesTable.initModel(SpielerMatchesTable.java:97)
	at module.playeranalysis.SpielerMatchesTable.refresh(SpielerMatchesTable.java:50)
	at module.playeranalysis.SpielerAnalysePanel.showSelectedPlayer(SpielerAnalysePanel.java:248)
	at module.playeranalysis.SpielerAnalysePanel.access$100(SpielerAnalysePanel.java:40)
	at module.playeranalysis.SpielerAnalysePanel$2.itemStateChanged(SpielerAnalysePanel.java:92)
	at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
	at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
	at javax.swing.JComboBox.contentsChanged(Unknown Source)
	at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by akasolace** [comment] 2020-01-26 16:56
@tychobrailleur @pierpaolocira @yaute74 does one one of you got a player in hall of fame to tackle that issue ?   If not I will have to ask for a database on HT forum.

**Comment by tychobrailleur** [comment] 2020-01-26 17:35
Nope, unfortunately I have started playing again only recently. ;-)

**Comment by wsbrenk** [comment] 2020-01-26 19:01
tried with 3 of my hall of fames players to reproduce that bug - didn't get an out of bound exception

**Comment by yaute74** [comment] 2020-01-26 19:10
@akasolace not for me

**Comment by akasolace** [comment] 2020-01-26 20:50
@LEOSCHUMY  could you please share your database ?

**Comment by LEOSCHUMY** [comment] 2020-01-26 21:02
Yes, I can but not before tomorrow night.
How do I send you it? By mail or uploading It on pubblic space (as WeTransfer)?

**Comment by LEOSCHUMY** [comment] 2020-01-27 20:02
[db_singleUser-2020-1-27.zip](https://github.com/akasolace/HO/files/4119089/db_singleUser-2020-1-27.zip)

**Comment by akasolace** [comment] 2020-01-28 10:59
> If you do get a db, I am happy to look into that one.

@tychobrailleur we now have a db :-)  thank you !

**Comment by tychobrailleur** [comment] 2020-01-28 13:23
Perfect, thanks.  Will look into it.

**Comment by tychobrailleur** [comment] 2020-01-28 20:35
I can reproduce the issue with the uploaded db.  For those players there seems to be missing `MATCHDETAILS`, e.g.: 

```
SELECT * from MATCHDETAILS WHERE MATCHID = 637009226
```

which is fine [there](https://www97.hattrick.org/Club/Matches/Match.aspx?matchID=637009226).

![Screenshot 2020-01-28 at 19 26 37](https://user-images.githubusercontent.com/114285/73301451-b448d680-420a-11ea-81f4-7e3df7d67eca.png)

A quick fix is to re-download the match details when we find out they are missing.  I'm wondering however if it wouldn't be better to do this at startup?

**Comment by akasolace** [comment] 2020-01-29 10:36
@LEOSCHUMY can you please it works with latest artefacts

Thank you

**Comment by LEOSCHUMY** [comment] 2020-01-30 18:35
It works!
Thanks

**Comment by akasolace** [comment] 2020-01-30 19:19
ok great I close the issue then !

**Closed by akasolace** 2020-01-30 19:19 UTC
Labels: status: needs test
