### ISSUE TITLE
Small Font in HO

### ISSUE THREAD

**Issue by AirForce2019** [akasolace/HO#65] opened 2019-01-01 18:04 UTC
Good morning, I have an ASUS with 4k video resolution and just open I have 1.435 visualize it with small fonts. I know it's a developer problem. You should release a version of HO for 4k resolutions. Do you let me know if a new version will be released with this integration? Thank you.
I can not even load the team, because the dialog box is small and does not give me the download button

**Comment by AirForce2019** [comment] 2019-01-01 18:09
[Schermata.docx](https://github.com/akasolace/HO/files/2719539/Schermata.docx)

**Comment by DavidatorusF** [comment] 2019-01-01 18:36
@akasolace don't know if it's usefull but... I let you have a look at 
https://sourceforge.net/p/ho1/tickets/5/

**Comment by akasolace** [comment] 2019-01-01 20:04
I think it is not a complex one to solve. 
Startup script should excplicilty let the OS do the upscaling.

**Comment by yaute74** [comment] 2019-01-04 20:42
@AirForce2019 do you try the "system" theme ?

**Comment by akasolace** [comment] 2019-01-06 20:12
@AirForce2019 

can you please tell me if the following steps are solving your issue: 

1. For both ``java.exe`` **and** ``javaw.exe`` likely found in ``C:\Program Files\Java\jre(version#)\bin``
2. Right click on it and select -> Properties
3. Go to Compatibility tab
4. Check Override high DPI scaling behavior.
5. Choose Scaling performed by ``System``
6. Click OK

**Comment by Synthespian** [comment] 2019-03-19 22:24
Confirmed.  The above does solve the issue for me.
For the record, the application was not scaling even if I put it on a smaller resolution monitor.

**Comment by akasolace** [comment] 2019-03-19 23:21
@Synthespian ok thank you for the feedback.
Hence, we can easily fix this via launch script by passing the appropriate parameter to javaw

**Comment by mistermax80** [comment] 2019-10-02 16:53
@akasolace It is easy to resolve?

**Comment by akasolace** [comment] 2019-10-02 18:55
@mistermax80 I won't bother because this will be fixed when we switch to java 11, which should happen after 2.0 is release

**Comment by akasolace** [comment] 2019-10-02 18:56
should be fixed when #106 is implemented

**Comment by akasolace** [comment] 2020-05-07 12:49
I put the milestone to backlog/someday for 2 reasons:
   - moving to java 11 might solve it
   - limited user feedback on this one
After a while we could simply decide to remove it

**Comment by tychobrailleur** [comment] 2020-06-03 21:12
The font size can be adjusted in preferences:

![Screenshot 2020-06-03 at 22 08 26](https://user-images.githubusercontent.com/114285/83689359-d0101f00-a5e6-11ea-80c3-e16c6616889d.png)

![Screenshot 2020-06-03 at 22 09 40](https://user-images.githubusercontent.com/114285/83689445-f59d2880-a5e6-11ea-9f55-0b8dc9302745.png)

This should work across all themes on the master branch.

Does this help?

**Comment by akasolace** [comment] 2020-06-04 08:24
for some this was not working ... I think it was a java error that should be fixed by the recent bump in version ...

**Closed** 2020-11-12 15:56 UTC
Labels: reso: info needed
