### ISSUE TITLE
[BUG] Team spirit and confidence are incorrect for tournament venue

### ISSUE THREAD

**Issue by velikodsky** [akasolace/HO#838] opened 2020-12-31 11:56 UTC
**Describe the bug**
When selecting the Venue "neutral (Tournament/Non-official)" in Lineup, the fields "Team spirit", "Sub of team spirit", "Confidence" became disables and are set to content/wonderful. This is correct. However, the parameters are not really changed: the predicted ratings are calculated with previous values of the parameters. One need to set them manually:
1) set Venue to "derby away";
2) set Team spirit to "content";
3) set Confidence to "wonderful";
4) set Venue to "neutral (Tournament/Non-official)".
After this operations, the predicted ratings are changed to correct ones.

**Platform information:**
 - OS: Arch Linux
 - Version HO-4.1.3310.2-portable-unix

**Comment by akasolace** [comment] 2020-12-31 16:54
hello,

can you please check if this bug still exist with the latest development version ? Please install it separetly along your current install as this version is still notvery well tested.
But I can't reproduce the issue you are describing with this version. 
Thank you

**Comment by velikodsky** [comment] 2020-12-31 19:18
Yes, the bug is still exist in HO 5.0 DEV (r3351).

1. After "File -> Download" I have:
Venue = Home
Team spirit = irritated
Confidence = poor
Midfield = 4.27
Right/central/left attack = 8.51/3.59/6.38

2. Setting "Venue = Tournament" changes Midfield but not Attack:
Team spirit = content
Confidence = wonderful
Midfield = 3.60
Right/central/left attack = 8.51/3.59/6.38

3. Setting "Venue = Home" reverts all parameters to Step 1.

4. Setting "Team spirit = content" results in: 
Midfield = 5.54

5. Setting "Confidence = wonderful" results in: 
Right/central/left attack = 10.13/4.18/7.55

6. Setting "Venue = Tournament" changes Midfield only: 
Team spirit = content
Confidence = wonderful
Midfield = 4.63
Right/central/left attack = 10.13/4.18/7.55

Thus, the ratings are different in Steps 2 and 6.

P.S. I downloaded HO-5.0.3351.0-portable-unix-DEV-JRE and additionally installed JRE 15 (because HO-5.0.3351.0-portable-unix-DEV-JRE contains JRE 14 only).

**Comment by akasolace** [comment] 2021-01-01 12:14
@velikodsky both bugs should be fixed (I mean also the bundled JRE). I will wait for your confirmation before closing this ticket.

**Comment by velikodsky** [comment] 2021-01-01 14:09
I confirm that both bugs are fixed in r3354. Thank you!

However, there is another problem now: when I go from Tournament venue to Home venue, Time spirit and Confidence are not changed and keep content/wonderful value. May be, they should reset to their current values. Or alternatively, there should be a way to reset them manually without downloading data.

**Comment by akasolace** [comment] 2021-01-01 17:12
> Or alternatively, there should be a way to reset them manually without downloading data.

Yes this is exactly what I was planning to do. I will add a button "reset to current values"

**Closed** 2021-01-01 17:12 UTC
Labels: status: needs test, type: bug

**Comment by akasolace** [comment] 2021-01-01 19:34
@velikodsky 

I made something like this

![image](https://user-images.githubusercontent.com/1136496/103445134-b9ab6e00-4c70-11eb-874a-6aef4ce331f1.png)

**Comment by velikodsky** [comment] 2021-01-01 19:39
> I made something like this

@akasolace 
Oh, good! It shall be convenient.
