### ISSUE TITLE
[BUG] Best position and AutoLineup are not in sync when using darklaf theme

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#744] opened 2020-10-21 13:15 UTC
**Describe the bug**
Activating or deactivating the autoLineUp flag for a player causes activation or deactivation the autoLineUp flag for another player.

**To Reproduce**
see clip in zip-file

**Screenshots**
[HO! - Hattrick Organizer 4.0 r3266 - Unterhose Kairo - 14.0.1 2020-10-21 15-11-27.zip](https://github.com/akasolace/HO/files/5416048/HO.-.Hattrick.Organizer.4.0.r3266.-.Unterhose.Kairo.-.14.0.1.2020-10-21.15-11-27.zip)

**Platform information:**
 - OS: [Windows 10 pro (10.0.19041 Build 19041)]
 - Version (Hattrick Organizer 4.0 r3266)

**Additional context**

**Comment by akasolace** [comment] 2020-10-21 14:55
@johari75 I can't reproduce. Something should be wrong with your database. Can you share it?

**Comment by akasolace** [comment] 2020-10-22 07:54
@johari75 yes please as a zip file. You only have one team, right ?

**Comment by johari75** [comment] 2020-10-22 07:57
@akasolace yes, I have only one team. My db folder is to big. 27 MB zipped

**Comment by johari75** [comment] 2020-10-22 08:12
@akasolace Here you are
[20201022_UnterhoseKairo_db.zip](https://github.com/akasolace/HO/files/5421203/20201022_UnterhoseKairo_db.zip)

**Comment by akasolace** [comment] 2020-10-22 16:22
@tychobrailleur @weisJ  I checked this one and the error comes from darklaf. The mouse pressed events are not detected correctly (at least for boolean cells I am not sure for other). Events are not always detected sometime and the reported value is incorrect: https://github.com/akasolace/HO/blob/733405bb6404efeec3eeddd5a09045885bcaad88/src/main/java/module/lineup/AustellungSpielerTable.java#L51


**with nimbus:**  best position and autolineup are in sync across the app

![EVdgy7YZA1](https://user-images.githubusercontent.com/1136496/96901114-20ebbb80-1493-11eb-83c0-4d24efcd147b.gif)


**with darklaf:**   best position and autolineup are not in sync across the app

![GeXRhbrYAp](https://user-images.githubusercontent.com/1136496/96901284-5b555880-1493-11eb-9864-4ef4e8ab8274.gif)

**Comment by weisJ** [comment] 2020-10-23 15:39
Relying on a mouse released event to be triggered isn't really the best option here. Lafs don't need to guarantee that the `mouseRelease` event will be send to the `JTable`. In fact almost all the time this event will be consumed by the editing component (which is happening in darklaf). 

I would recommend to install a [`TableModelListener`](https://docs.oracle.com/javase/7/docs/api/javax/swing/event/TableModelListener.html) on the tables model and react to the events in there (Which is in fact currently broken in darklaf, but I am working on updating the table value as soon as the editor value changes).

**Comment by akasolace** [comment] 2020-10-26 07:54
@tychobrailleur when you got a bit of free time again it could be nice if you can have a look at this one. It is a blocking one for 4.0 and so far I did not manage to fix it ....

**Comment by weisJ** [comment] 2020-10-27 06:54
Version 2.5.0 of darklaf should resolve this issue as is (i.e. without further changes). Though I would still highly recommend to change the approach as suggested above.

**Comment by akasolace** [comment] 2020-10-27 07:27
@weisJ ok good to know cause I tried to do it via the TableModelListener but so far without success. Any idea when 2.5 will be released?

**Comment by johari75** [comment] 2020-10-27 10:26
Is there anything I can do to support you or to test your solution anyhow?

**Comment by akasolace** [comment] 2020-10-27 11:41
@johari75  you should be able to test with the next beta ...

**Comment by akasolace** [comment] 2020-10-27 22:11
@weisJ @tychobrailleur  in this example the Jtable model is a TableSorter. AddingTableModelListener to the Jtable only captures changes on sorting (see below) 
 
~~~
getModel().addTableModelListener(new TableModelListener() {
tableSorter.addTableModelListener(e -> System.out.println("Table Changed 1 !"));
tableSorter.getModel().addTableModelListener(e -> System.out.println("Table Changed 2 !"));
~~~

"Table Changed 1 !" is displayed if I change sorting of some columns
but "Table Changed 2 !" is never displayed

I am not sure if in such case I can use TableModelListener .... any ideas ?

**Closed** 2020-10-27 22:32 UTC
Labels: scope: GUI, type: bug

**Comment by weisJ** [comment] 2020-10-28 08:49
Did you try this with the new darklaf version?

**Comment by akasolace** [comment] 2020-10-28 09:19
> Did you try this with the new darklaf version?

yes it fxed the issue !

> Also it like TableSorter is a custom table model for HO. So if sorting events aren’t propagated then there needs to be changes made to TableSorter itself.

yes I will try again to look at this in the future ... I opened a ticket for this (https://github.com/akasolace/HO/issues/752)

@weisJ  thank you for your help !
