### ISSUE TITLE
[eFEAT] HO lineup can suggest same role or other tricks for special event

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#299] opened 2019-12-01 16:18 UTC
In manual at this section "special event": https://www.hattrick.org/en/Help/Rules/SetPiecesAndSpecial.aspx

Are reported the condition for realize special event, in HO new we can see only icons (x or v) for special event on wheter:
![image](https://user-images.githubusercontent.com/15519907/69916684-4b3d2080-145e-11ea-96c6-8dc09900cfe3.png)
I don't sure the overcrowding penalty are considered.

The idea is: during lineup setup, HO can suggest particula notice, in order to help user to avoid negative situation and suggest positive situatons.

@yaute74 @akasolace @DavidatorusF 
What do you think?

**Comment by akasolace** [comment] 2019-12-01 19:33
@mistermax80 what additional info would you like to provide?  Hoover message giving more details like "Strong players are loosing XXX under the Sun ...." like the full thing ?

> I don't sure the overcrowding penalty are considered.
It is considered in prediction rating

**Comment by mistermax80** [comment] 2019-12-01 22:28
Yes the idea can be that... If you think this can be interesting I can list all.

**Comment by akasolace** [comment] 2019-12-02 07:25
So it is what you had in mind?

**Comment by mistermax80** [comment] 2019-12-02 12:37
@akasolace 
I think HO should be an tool that helps the users. The users can not have in mind every conditions to check, and for me HO can help user to remind some things and take the correct choices.
In order to explain better what I want say, the broke elevator features on rating in time, I don't know what I use that information, but if HO suggests some advice it can be the difference respect to the tool that HT already give us.

**Comment by akasolace** [comment] 2019-12-02 13:29
@mistermax80 I just what to understand what you have in mind exactly with this new feature request:
   1) simply as I stated above, add description of the good/bad weather event indication (simple to do)
   2) consider the weather for the calculation of the contribution rating (more difficult to do)
 
In case it is 2), how to implement it? A possible approach could be:
    - calculate contribution for each player for all weather condition 
    - on all tabs but lineup display performance w/o weather event
    - on lineup dropbox, display info with related weather information
    - amend rating calculation accordingly

Clearly approach 2 is "very" heavy whereas approach 1 is very simple.

**Comment by mistermax80** [comment] 2019-12-03 14:42
@akasolace the approac is 1) only suggest...
for overcrowding i'm refering to:

> You will suffer an overcrowding penalty if you field two or three players having the same combination of specialities and positions, among the following types: technical defensive forwards, powerful normal forwards and powerful defensive inner midfielders. If you field two players of the same type, you will suffer a penalty on their contribution (4% each). If you field three of them, the penalty will be bigger (7.5% each).

**Comment by akasolace** [comment] 2019-12-03 15:43
@mistermax80 

>  the approac is 1) only suggest...  

ok

> for overcrowding i'm refering to:

overcrowding is already considered in rating calculation

**Comment by wsbrenk** [comment] 2019-12-07 11:51
concerning wheater i found the following
- one could download the regions current wheater and next day prediction of the match 
- if none of these would match the match date the prediction value should set the default of a user choice combobox selecting the wheater which controls the rating predictions
- if one matches the wheater selection box could be disabled (or not or only if it is the current wheater)
- i don't know if the wheater contribution to the ratings is well known of if so it's easy to implement

the first 3 items should not be so hard to be implemented.

**Comment by akasolace** [comment] 2019-12-07 12:26
Item 4 has indeed been implemented. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment] 2019-12-08 00:15
In additional to weather conditions, I had in mind to suggest the following insight (I extracted some from HT Manual see post 1 of this issue):

> 1) example: Technical wingers, inner midfielders and forwards **can create chances** if an opposing defender or inner midfielder is a head specialist (the latter doesn’t have to be in the exact opposite slot). Moreover, every technical defender and wing back will **give you a small chance to create a non-tactical counter attack** from a missed normal chance of your opponent. The higher the passing of the defender, the bigger the chance.
2) example: Experience: experienced forwards **can score using their experience**. Inexperienced central defenders and wing backs can give their opponents an extra chance.
3) example: Powerful forwards, if playing normal (also called power forwards) can put their bodies in the right place, **forcing a second chance to shoot and score after a normal chance for your team has been missed.** They will need sufficient playmaking and scoring skills to do that. Note that their physical play can result in yellow cards; however, if your player has already been carded, he will tread more carefully in these situations.
4) example: **You will suffer an overcrowding penalty** if you field two or three players having the same combination of specialities and positions, among the following types: technical defensive forwards, powerful normal forwards and powerful defensive inner midfielders. If you field two players of the same type, you will suffer a penalty on their contribution (4% each). If you field three of them, the penalty will be bigger (7.5% each).

I don't know how to implements this, we can see how foxtrix suggest some this insigth:
![Schermata 2019-12-08 alle 01 13 47](https://user-images.githubusercontent.com/15519907/70382183-10545480-1958-11ea-9406-9a49f247e20f.png)

**Comment by akasolace** [comment] 2019-12-08 11:27
@mistermax80 this is what is available in tool Special Events
maybe we can make some of tht information available in hoover message in players tabs....

**Comment by wsbrenk** [comment] 2019-12-08 11:33
yesterday i started implementing Regiondetails to load weather infos from HT

**Comment by wsbrenk** [comment] 2019-12-08 11:38
concerning special events it again is necessary or useful to get infos about the oppenent team - up to now i do not have a good idea how to handle that. until now the lineup is completly disconnected from the matches until the up or download happens

**Comment by mistermax80** [comment] 2019-12-08 12:50
We are discussing in #215

**Comment by wsbrenk** [comment] 2019-12-12 22:33
one first simple step could be to load regionIds of the upcoming matches if it is not a Home match. 3 simple methods could give info about match location:
isHome {return regionId==-1}
isDerby {return regionId == OwnRegionId}
isAway {return regionId>=0 && regionId != OwnRegionId}
next step would be to load RegionDetails of the Match to preset weather combo box.

**Comment by akasolace** [comment] 2019-12-14 16:12
@wsbrenk so the idea would be when refreshing lineup for upcoming match:
   - If match is today or tomorrow:
      - if home get own region id 
      - else: look ID of opponent, look region ID of opponent from team details
               : determine if it is a derby (this was never implemented in HO, it could be the tight time to do it)
      - get weather of  selected region ID

     - if match is after tomorrow:  we revert to default weather and maybe we indicate a "?" next to it to indicate it is unknown.

Is it what you had in mind?  In that case I think this might be 2 separate tickets and 2 separate PR
 1) "fetch weather information of upcoming match"
 2) "determine if away game is a derby"

This ticket would remains open and might be tackle afterward.

**Comment by wsbrenk** [comment] 2019-12-14 22:18
@akasolace yes, these 2 points i think are necessary to examine more influences to ratings and effects of special events. i think it is a good idea to split it in multiple tickets.
today i started trying to download arenaId and regionId of upcoming matches.

**Comment by wsbrenk** [comment] 2019-12-15 14:36
yesterday i thought that i could treat all match types with the help of 2 values (arenaId, regionId). Today I came up with the neutral match types. An approach with 2 values ​​would be this:
// TYPE				|arenaId 		|region Id
// HOME				|HomeArenaId	|-1
// AWAY				|!= HomeArenaId |>0
// NEUTRAL			|<-1			|>0
// DERBY_NEUTRAL	|<-1			|>0
// DERBY_HOME		|HomeArenaId	|HomeRegionId
// DERBY_AWAY		|!=HomeArenaId	|HomeRegionId
// DIVISION_BATTLE	|0				|0
// UNKNOWN			|-1				|-1

Neutral derby and neutral match could not be distinguished. If that's bad, we need a 3rd value.
Handling it with 4 values (arena, region, derby, neutral) would make it more readable.

**Comment by akasolace** [comment] 2019-12-15 14:52
> Handling it with 4 values (arena, region, derby, neutral) would make it more readable.

yes I think it would be more readable

**Comment by wsbrenk** [comment] 2019-12-15 16:11
thanks for the suggestion. I will do 4 values

**Comment by wsbrenk** [comment] 2019-12-21 10:39
Progress Report

download from matchkurzinfo loads arenaId, regionId, isDerby, isNeutral, Weather, WeatherForecast (HAPPENED, TODAY, TOMORROW, UNSURE, NULL)
Lineup.Local has got a new value NEUTRAL, LOCAL_AWAY is also set if the derby is a home game.
Weather information is also included in the lineup, but I still don't know how I can transfer this data to the AufstellungAssistantNewPanel. I am currently doing research on this.

**Comment by wsbrenk** [comment] 2019-12-21 15:25
a first version of the weather combo box init is implemented.
I am not sure if this is a reasonable solution, because I don’t have much idea about java GUI programming. Found that the AssistantPanelNew is not in use and wondered why. In addition, there is no refresh method in the AssistantPanel, where I could have easily installed it.
So I tried the constructor. Would be grateful if you could offer a better solution.

**Comment by wsbrenk** [comment] 2019-12-22 11:18
i looked for further non weather depending special events and devided in two groups. one group does not depend on the opponent team the second one does:

Group 1:
a) Experience less than weak (Mistermax80 example 2)
b) unpredictable player
c) winger + head/scoring
d) powerful forward (example 3)
e) powerful defensive inner midfield
f) counter attacks
g) long distance shots

Group 2:
a) stamina
b) number of head specialists
c) fast 
d) technician/head (example 1)

Question is, what to attack first. Examine opponents lineup(s) to handle group 2 or start with group 1?
My idea is to start with group 1.

**Comment by mistermax80** [comment] 2019-12-22 11:44
Yes, It Is that I had in mind.
For me go ahead with group 1

**Comment by akasolace** [comment] 2019-12-23 11:27
@wsbrenk hello, I am currrently travelling and I don't have really the time to go into details but I see this ticket is becoming more and more ambitious.
I am not really familiar with AssitantPanel and the GUI part is also not the part I am the more confortable with, if @brokenelevator comes by he might give advices.

@wsbrenk can you explain again what you are planning to do exactly for non weather event? Display some messages depending of the tactic?

**Comment by wsbrenk** [comment] 2019-12-23 11:59
@akasolace hello, my first idea is to generate a list of SpecialEventsPrediction with one entry of each possible event. Attributes of these entries could be 
- name of the event type
- responsable position of the lineup
- list of other involved positions
- chance creation probability (> 0, if positive event; < 0 if negativ event) 

as a very first guess i will set probability to +1 or -1 and we could easily display the list near the lineup.
After further investigation one could introduce realistic probability values and aggregate the whole list and we could display an overall chance creation value.

This are my ideas up to now - more ideas are welcome.

**Comment by wsbrenk** [comment] 2019-12-23 12:03
As the very first example i would create the ExperienceEventPrediction with a negative impact for each player with experience less than wretched (2).

**Comment by wsbrenk** [comment] 2019-12-23 13:05
i commited a very preliminary scetch of what i'm planning to implement:
https://github.com/wsbrenk/HO/commit/ec416f3d7e2f951252072e5b6894b28f44c6d772

PLease have a look on it and tell me if i'm on the "wood way" (wrong track).

**Comment by mistermax80** [comment] 2019-12-23 16:38
> @wsbrenk hello, I am currrently travelling and I don't have really the time to go into details but I see this ticket is becoming more and more ambitious.
> I am not really familiar with AssitantPanel and the GUI part is also not the part I am the more confortable with, if @brokenelevator comes by he might give advices.
> 
> @wsbrenk can you explain again what you are planning to do exactly for non weather event? Display some messages depending of the tactic?

Yes I understand, but if we able to implement this suggestions, I think it will be useful!!!!

**Comment by wsbrenk** [comment] 2019-12-24 10:16
progress report:

- lineup.setSpecialEvents calculates a list of possible SEs
![sepred](https://user-images.githubusercontent.com/11821502/71408280-e41a2280-263d-11ea-94ae-4dc02d686fab.jpg)

next possible steps:
- investigate realistic probability values, now they are phantasy numbers, only the sign should be correct.
- display the list in the lineup panel
- handle SEs of group 2 which need the opponents lineup details, not only the players with there specialities, but also a guess of there skills.

merry christmas alltogether

**Comment by akasolace** [comment] 2019-12-29 17:08
@wsbrenk thank you for the update
hope you are also having a nice time off. Looking forward to see what will come out of this ...

**Comment by wsbrenk** [comment] 2019-12-30 10:22
i'm stuck with the next step since some days. team analyzer should have the needed infos concerning upcoming opponents and their lineups in previous matches which could be used to estimate se probabilities but up to now i don't see that they are usable. they seem to be completly different to the other lineup, player and rating classes.
Currently i'm not sure if it is easier to use TA ui and display the SE list beneath the TAs rating panel or to implement opponent and match selection in the lineup panel and display the SE list like @Mistermax80 suggested.
gui programming is a tough nut for me.

**Comment by akasolace** [comment] 2019-12-30 11:31
@wsbrenk  as you can see in all my messages above, I was never sure what is/was the expected outcome of this ticket. 
At first I thought it would simply be displaying additional information on SE while hoovering a player with specialty (SE that could depend or not on weather). But it seems it is bigger than that. 
@mistermax80 I think it is important to realign the objectives ...
@DavidatorusF @yaute74 maybe you have some ideas concerning this one ....

**Comment by yaute74** [comment] 2019-12-30 20:48
Maybe we can have a list of options: Void/Sun/Rain (by default void is select).
If we click on Sun or Rain we highlight players concerning by the SE and modify the rating +/- 5 %

**Comment by akasolace** [comment] 2019-12-31 07:54
> Maybe we can have a list of options: Void/Sun/Rain (by default void is select).
If we click on Sun or Rain we highlight players concerning by the SE and modify the rating +/- 5 %

Either I am missing something or it is exactly how it is currently implemented

**Comment by mistermax80** [comment] 2019-12-31 08:06
I think it is already implemented the weather beaviuos...
For line up: My idea (as initial improvement) list some advises for the uses in order to help the users to enhance the lineup, as example:
If you have a forward technical, hi can suggest to set this player as forward technical defence...
Other example: if you have an midfielde powefull, HO can suggest to set position as defence in order to setup as Powerful inner midfielders...
My suggestion is list all messages we want show to users and so we can decide how expose these to users.

For match analyzed: we can show the opponent players specialist and in the future we can think to expose messages for help users to defence by opponent special events.

**Comment by wsbrenk** [comment] 2019-12-31 10:16
thank for your support.
- the weather part is done i think. on my feature#299 branch the weather will be preselected by the regionDetails.
- most of the other special events need informations about the opponent team. in the moment i use the team analyzer to select the opponent team and its match to compare with. i found some classes which where designed to estimate opponent skills but i really don't know anything about there state up to now (OppPlayerSkillEstimator). They aren't used anywhere. 
- my idea is to present the list of special events beneath the rating panel in the team analyzer at first

**Comment by wsbrenk** [comment] 2019-12-31 10:50
I will continue debugging now. If someone has information about the OppPlayerSkillEstimator class, I can use it very well.

**Comment by akasolace** [comment] 2019-12-31 10:54
@wsbrenk  also be informed that my work on #309 makes me refactor all the MatchHighlights class.
I am not sure whether or not this will interfere with that ticket.

> If someone has information about the OppPlayerSkillEstimator class, I can use it very well.

I reply to you on slack

**Comment by wsbrenk** [comment] 2019-12-31 10:57
@mistermax80 

> For line up: My idea (as initial improvement) list some advises for the uses in order to help the users to enhance the lineup

this could be one solution. a kind of advisor wizard. this can definitely be an add on to the SE list I have planned. my idea is to calculate the se list with their probabilities comparable to the rating predictions and present the changes if the user changes his own lineup or the selected lineup of his opponent.

**Comment by wsbrenk** [comment] 2019-12-31 11:04
@akasolace 

>  also be informed that my work on #309 makes me refactor all the MatchHighlights class.
I am not sure whether or not this will interfere with that ticket.

up to now i do not use the MatchHighlights. 
i found your response on slack. that helps because I now know that it is a preliminary class. Let's see what the debugging session will give us.

**Comment by yaute74** [comment] 2019-12-31 11:36
@akasolace sorry to be honest I never use it

**Comment by akasolace** [comment] 2019-12-31 11:51
> Edit: the rating value don't change, we have always the same value 

are you sure ? Last time I checked it was working well ... if confirmed this is a bug/regression

**Comment by yaute74** [comment] 2019-12-31 11:59
I have just an icon (red or green) but no change on my rating

**Comment by wsbrenk** [comment] 2019-12-31 12:26
@yaute74 

> I have just an icon (red or green) but no change on my rating

you are right if you refer to the ratings of the individual player. The team ratings are changed.

**Comment by yaute74** [comment] 2020-01-01 12:16
@wsbrenk yes I refer to individual player

**Comment by akasolace** [comment] 2020-01-02 07:29
@yaute74 @wsbrenk ah ok now I got the problem but it might be difficult to fix it ... I created #343 for that specific issue

**Comment by wsbrenk** [comment] 2020-01-02 11:20
progress report:

the current special event list i'm working with, is this [one](https://devblog.hattrick.org/2017/12/a-new-match-engine-odyssey/)

The framework for determining the special events has been ready for testing since yesterday. The class that can determine the strength of the opponents looks particularly promising.
From the above referenced list I have programmed the quick scores and quick pass events since yesterday. Took a full working day. If you look at the rest of the list, you will find that at least 5-10 more days are required for the other events.
Further open points (beside testing):
- aggregation of the special event list (i think it could get very lengthy)
- display it

**Comment by akasolace** [comment] 2020-01-02 12:01
@wsbrenk 

> The class that can determine the strength of the opponents looks particularly promising.

can you tell me what this class is doing exactly?

> I have programmed the quick scores and quick pass events since yesterday.

what does it mean exactly? I am not clear on what you are planning to deliver ...

> at least 5-10 more days are required for the other events.

This will go into HO 3.0, so you have plenty of time ...

**Comment by wsbrenk** [comment] 2020-01-02 13:08
> can you tell me what this class is doing exactly?

it has a function which uses the info from MatchLineup as input (stamina, form, tsi, wage etc) and calculates the players skills very well. One single test with info of my own goalkeeper delivered exact GK- and Def-skill values.

>  I am not clear on what you are planning to deliver ...

for the users i want to display a list of possible events depending on his lineup and selection of the opponent team and matchlineup to compare with. If he changes his lineup or selects another match of his opponent, the result should be updated.

for the devolopers it is a framework that fetches the own current lineup, examines opponent lineup from selection descriped above, calculating the opponent players strength. Then it runs 2 analyses, one for each team lineup, calling a list of registered analyzer classes to analyze each position of the lineup. Analyzers are specialized for one special kind of event, for example Quick-scoring and Quick-passing. They create special event predictions, if the conditions matches. These are collected in two lists, one for each team.

**Comment by wsbrenk** [comment] 2020-01-02 13:16
it is probably a good idea to start developing the gui to give a first impression of what should come out in the end.

**Comment by wsbrenk** [comment] 2020-01-02 14:12
![specialEventGui](https://user-images.githubusercontent.com/11821502/71671061-3829b300-2d72-11ea-994e-0f19815d1902.png)

ready;-)

**Comment by akasolace** [comment] 2020-01-03 07:11
ah now I see ... it is indeed much clearer with a GUI !  It looks very neat !

**Comment by wsbrenk** [comment] 2020-01-03 14:37
![specialeventpanel](https://user-images.githubusercontent.com/11821502/71728712-1990ee00-2e3e-11ea-98a3-d8106f1c2a2b.jpg)

nearly 2 goals for me, not one for the opponent;-)

today i learned a lot about Layouts Splitpanes and stuff like this.
in next time i would like to concentrate on analyzing special events, to get nearly realistic numbers.

To get the table more beautiful, I need good suggestions and the best support from swing experts.

**Comment by akasolace** [comment] 2020-01-03 14:56
maybe it will be best to have just a summary of Special Events by default: like a one-liner indicating the results. Then we can have next to it either an icon allowing to open a popup window with all the details or a big hoover message with all the detailed information ...
Again I was not sure what it would look like but it is a very neat addition.  
Regarding the probability, it there a chance to make it relatively accurate? Are the rules really specified somewhere?

**Comment by wsbrenk** [comment] 2020-01-03 15:20
there are a lot of statistics and investigations on this in the english global, especially this one: [https://www.hattrick.org/Forum/Read.aspx?t=17161178&v=0&a=1&n=1](https://www.hattrick.org/Forum/Read.aspx?t=17161178&v=0&a=1&n=1)

**Comment by wsbrenk** [comment] 2020-01-03 23:39
> maybe it will be best to have just a summary of Special Events by default: like a one-liner indicating the results. Then we can have next to it either an icon allowing to open a popup window with all the details or a big hoover message with all the detailed information ...

good idea: a tree view, collapsed onto a single result line, next level could be the event types, then the single events - maybe the team in between?!

**Comment by akasolace** [comment] 2020-01-04 12:03
> good idea: a tree view, collapsed onto a single result line, next level could be the event types, then the single events

that would be super nice ... no idea how to do this in SWING but I guess it is feasible

> maybe the team in between?!

no sure what you mean here?  You mean moving it to the right side?  if it is the case I think it will be a lot of work, no ?

**Comment by wsbrenk** [comment] 2020-01-04 14:19
i meant an extra tree level where i could collapse alls ses of my or opponent team.

**Comment by akasolace** [comment] 2020-01-04 18:11
> i meant an extra tree level where i could collapse alls ses of my or opponent team.

ok I see, sounds nice

**Comment by wsbrenk** [comment] 2020-01-05 13:36
At the moment i have the impression that the skills of the opponents are somewhat underestimated

therefore an idea for further sub project/ticket:
- show the list of calculated opponent players with their calculated skills
- give users a chance to overwrite the calculated values (recalc tsi and wage)

with that
- users could optimize special events prediction
- developpers could optimize skill calculation more easily (currently the skills will be logged as debug level, but there is no chance to easily simulate variations of those numbers)

@akasolace how to handle such ideas. is it worth to create extra tickets for those. how could one set it as an sub ticket of this one? or should it remain with a note

**Comment by wsbrenk** [comment] 2020-01-11 16:14
to monitor the progress and to do some requirements tracking, i copied the Ht special event specifications in this document: [SpecialEventsPrediction.java](https://github.com/wsbrenk/HO/blob/feature%23299/src/main/java/core/specialevents/SpecialEventsPrediction.java)

TODOs and DONEs marks current status.

I started with corner events now. I learned that they need the indirect set pieces ratings form attack and defence. i'm ready with downloading and adding these infos to the MatchDetails table.

@akasolace @mistermax80 @yaute74  Now I should still know how these ratings are calculated for the current lineup. is there anybody out there who knows this?

**Comment by akasolace** [comment] 2020-01-11 17:58
Your best shot is @DavidatorusF ... I would say it is simply the sum of SP  but I am not 100% sure ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DavidatorusF** [comment] 2020-01-12 18:13
best shot... of Vodka, no problem

the answer is an other story... sorry

**Comment by wsbrenk** [comment] 2020-01-12 21:04
i actually found it in the unwritten manual today.

**Comment by wsbrenk** [comment] 2020-01-19 13:32
i think the software is ready to start beta testing soon. I would be very happy if any of you would take over the alpha test.
up to now i didn't change the gui (the list view of the special event), since i think it is the best way to show the beta testers the results.
the effect of special events prediction is realized close to the specifications i found in the forum. Only a few are simplified a little but i hope they are still close to the effects described by the specifications.
some todos in the specifications are still left. for example the special event of the support player. in this case i think the effect has only impact on the ratings and will not create concrete goal events. 
I would like to leave such things for the discussions during a field test.
what do you suggest how we want to proceed?

**Comment by akasolace** [comment] 2020-01-19 19:01
I will be happy to test is ... as soon as I am done with my current task.
Hopefully next week !

**Comment by akasolace** [comment] 2020-01-21 09:31
@wsbrenk when you have a version you want me to test, please do a PR mentioning it is for testing only 
cheers

**Comment by akasolace** [comment] 2020-02-17 21:04
closed by #358

**Closed by akasolace** 2020-02-17 21:04 UTC
Labels: effort: high, reso: info needed, status: accepted/WIP

**Comment by akasolace** [comment] 2020-02-18 18:06
@wsbrenk  it is not working for me , I have nothing being displayed !
