### ISSUE TITLE
[eBUG] wrong training highlight when set different future trainings

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#296] opened 2019-11-29 00:49 UTC
![image](https://user-images.githubusercontent.com/15519907/69836596-36883f00-124a-11ea-9ecb-8cd9eb7f11c6.png)

The correct highlight is for the current training, in this case "passing" (ongoing week) and no "attack" (represet the last in future).

**Comment by mistermax80** [comment] 2019-11-29 17:16
@akasolace let me know what it is not clear, I will try to explain with differents words.

**Comment by akasolace** [comment] 2019-12-11 13:32
@mistermax80 I think I understand the issue, highlight should be on future training and not past training. What I don't get in you example is it seems that you have 2 differents kind of training set for the future. Is it correct ?
@yaute74 @mistermax80  @da  how do you suggest we treat this?

**Comment by yaute74** [comment] 2019-12-11 20:50
@akasolace @mistermax80 what I understand is, actully it highlight the futur training instead of current training.
If it's the case, for me it's a bug

**Comment by mistermax80** [comment] 2019-12-12 07:18
Yes You understand it.
For me the highlight player should be for training in current week.
It seems HO highlights the future last training.

**Comment by akasolace** [comment] 2019-12-12 07:40
@mistermax80 is it possible to set differents kind of trainings in the future? If not, it means that in HO we can only have one kind of training, the same for the current week and the future weeks, right?

**Comment by mistermax80** [comment] 2019-12-12 07:54
@akasolace 
No I think and How I used the future training it is serve to planning the future trining, infact in player details you can see the all the different future trainings. So you should leave as-is for me.
The current week it should the first of the future week.

**Comment by akasolace** [comment] 2019-12-30 08:21
If I understand @mistermax80 suggestion, it is a quick one.
@mistermax80 @yaute74 do you agree on the behaviour we want here?

**Comment by yaute74** [comment] 2019-12-30 20:49
@akasolace yes for me

**Comment by akasolace** [comment] 2019-12-31 07:56
ok then

**Comment by akasolace** [comment] 2020-01-28 10:56
@mistermax80 will you close this one shortly? 
@yaute74 in case mistermax does not close it, do you want to tackle it or shoud I remove it from 2.1 release? I am too busy on other part of the project at the moment ...

**Comment by wsbrenk** [comment] 2020-01-28 12:39
![trainingprogrnose](https://user-images.githubusercontent.com/11821502/73264484-374e3a80-41d3-11ea-914c-d1ab92147b93.jpg)

@akasolace for me it looks OK now. the current solution not only highlights the current training but all trainings planned in the future (except set piecing, which  would select all players). so the bug, that the current training is NOT selected is fixed (for me).

**Comment by akasolace** [comment] 2020-01-28 12:50
@wsbrenk  it is true that I don't really see what is wrong ...

@mistermax80, @yaute74  are we missing the point or should I close this one?

**Comment by akasolace** [comment] 2020-01-29 10:31
I close this one, @mistermax80 @yaute74  please feel free to reopen it if you thing there is still an issue here

**Comment by wsbrenk** [comment] 2020-02-08 23:15
I was able to reproduce the bug with my first team today. I was able to verify that the error is related to the fact that an average training speed is determined in order to determine the candidates to be selected. This is bad for current trainees if they only train for a few weeks and then no more.

**Comment by akasolace** [comment] 2020-02-09 19:38
@wsbrenk  ok I reopen the issue even if I am not 100% I understand what the bug is ...
Do you think this should/could be closed for 2.1 or should we target 3.0 for this one ?

**Comment by wsbrenk** [comment] 2020-02-09 22:10
@akasolace I'm trying to do a simple example. Let's say there is a 10 week training plan. First a week CV then 9 weeks PM. In this case, the forwards receive 10% training and are not marked.
If we would use the maximum trainingspeed, then forwards and inner midfield would marked green an wingers yellow.
This change would be very easy to do. 

As a consequence, all players would be marked green if in the future weeks either all types of training or one week set pieces were planned.

**Comment by wsbrenk** [comment] 2020-02-09 22:38
![grafik](https://user-images.githubusercontent.com/11821502/74111490-23241900-4b95-11ea-8f52-77947080b406.png)

since i'm planning set pieces for some weeks my  solution looks like this.

**Comment by akasolace** [comment] 2020-02-10 07:50
@wsbrenk ok I see I will merge your fix for 2.1 then ... thank you

**Closed** 2020-02-10 19:10 UTC
Labels: type: bug
