### ISSUE TITLE
[eBUG] Faulty ratings in HO

### ISSUE THREAD

**Issue by cheilson** [akasolace/HO#292] opened 2019-11-24 21:33 UTC
**Describe the bug**
When I select my best players in HO, it predicts 244 in Hatstats, however HT predicts 389 in hatstats. 

**To Reproduce**
1. Go to lineup page
2. Select same squad

**Screenshots**

**Platform information:**
 - OS: [Windows10]
 - Version 2.0 1414 (But had the same issue in earlier versions as well, but thought a clean install fixed it.

**Additional context**
Made a new clean install, I only imported the HRF files.

![2019-11-24](https://user-images.githubusercontent.com/52073695/69501954-4fbb8380-0f0a-11ea-90cd-2efa5c5b76d4.png)
![2019-11-24 (1)](https://user-images.githubusercontent.com/52073695/69501955-50541a00-0f0a-11ea-85c6-fdd057cb132b.png)
![2019-11-24 (2)](https://user-images.githubusercontent.com/52073695/69501956-50541a00-0f0a-11ea-9a35-bf2358f86d68.png)

Do you need the HRF files as well?

**Comment by akasolace** [comment] 2019-11-25 08:19
@cheilson , looks like your formula are broken,   can you try preference -> formula -> reset factors  ?

**Comment by cheilson** [comment] 2019-11-25 16:02
After messing around a lot, It looks alright now. I’ll be back if it happens again.

 

Fra: akasolace <notifications@github.com> 
Sendt: 25. november 2019 09:20
Til: akasolace/HO <HO@noreply.github.com>
Cc: cheilson <kejle@1145.dk>; Author <author@noreply.github.com>
Emne: Re: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

@cheilson <https://github.com/cheilson>  , looks like your formula are broken, can you try preference -> formula -> reset factors ?

**Comment by cheilson** [comment] 2019-12-01 17:33
And now it is back again.



Resetting formulas didn’t help.

I made a copy of the entire folder, would you like a zip copy?

 

 

Fra: Claus Kejlstrup <kejle@1145.dk> 
Sendt: 25. november 2019 17:03
Til: 'akasolace/HO' <reply@reply.github.com>
Emne: SV: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

After messing around a lot, It looks alright now. I’ll be back if it happens again.

 

Fra: akasolace < <mailto:notifications@github.com> notifications@github.com> 
Sendt: 25. november 2019 09:20
Til: akasolace/HO < <mailto:HO@noreply.github.com> HO@noreply.github.com>
Cc: cheilson < <mailto:kejle@1145.dk> kejle@1145.dk>; Author < <mailto:author@noreply.github.com> author@noreply.github.com>
Emne: Re: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

 <https://github.com/cheilson> @cheilson , looks like your formula are broken, can you try preference -> formula -> reset factors ?

**Comment by akasolace** [comment] 2019-12-01 19:31
@cheilson yes please, a zip of your database, screenshot of your HO Lineup as well as HT.

Thank you

**Comment by cheilson** [comment] 2019-12-02 20:56
Hi.

 

Its all here:

 

https://we.tl/t-0pC5FWAQ4k

 

 

 

Fra: akasolace <notifications@github.com> 
Sendt: 1. december 2019 20:31
Til: akasolace/HO <HO@noreply.github.com>
Cc: cheilson <kejle@1145.dk>; Mention <mention@noreply.github.com>
Emne: Re: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

@cheilson <https://github.com/cheilson>  yes please, a zip of your database, screenshot of your HO Lineup as well as HT.

Thank you

**Comment by akasolace** [comment] 2019-12-03 07:28
@pierpaolocira @konved 
Hello, does one of you want to investigate this one? First thing is to confirm whether or not there is an issue.

**Comment by pierpaolocira** [comment] 2019-12-04 21:50
@akasolace I don't have really time in this period, but al least I tried to reproduce.
I know that I will be considered as a dumb (in truth I'm not really an expert in Hattrick, and this is why I never went over V serie :) ), but I was neither able to find that "Match Order" web screen. My Hattrick looks quite different... or I'm looking in the wrong place.
<img width="791" alt="immagine" src="https://user-images.githubusercontent.com/11422667/70184545-52775f00-16e8-11ea-83c9-eaef96cc21b1.png">

**Comment by cheilson** [comment] 2019-12-05 04:59
Its the old match order interface. 




Få Outlook til Android







On Wed, Dec 4, 2019 at 10:51 PM +0100, "pierpaolocira" <notifications@github.com> wrote:












@akasolace I don't have really time in this period, but al least I tried to reproduce.

I know that I will be considered as a dumb (in truth I'm not really an expert in Hattrick, and this is why I never went over V serie :) ), but I was neither able to find that "Match Order" web screen. My Hattrick looks quite different... or I'm looking in the wrong place.

**Comment by akasolace** [comment] 2019-12-05 07:44
@pierpaolocira you need to select the new match order interface in HT preference.

However, you can't replicate HT values on your side so you will have to rely on @cheilson inputs. The idea is to see what is wrong with his HO that gives apparently values very off from HT.  I thought its FAKTOREN table was corrupted but apparently resetting the coefficients does not fix the issue which is really weired.

**Comment by cheilson** [comment] 2019-12-05 15:36
Todays result after download.

I’ll make a new zip of my DB so you can compare.

 

Fra: akasolace <notifications@github.com> 
Sendt: 5. december 2019 08:44
Til: akasolace/HO <HO@noreply.github.com>
Cc: cheilson <kejle@1145.dk>; Mention <mention@noreply.github.com>
Emne: Re: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

@pierpaolocira <https://github.com/pierpaolocira>  you need to select the new match order interface in HT preference.

However, you can't replicate HT values on your side so you will have to rely on @cheilson <https://github.com/cheilson>  inputs. The idea is to see what is wrong with his HO that gives apparently values very off from HT. I thought its FAKTOREN table was corrupted but apparently resetting the coefficients does not fix the issue which is really weired.

**Comment by cheilson** [comment] 2019-12-05 15:38
And the database:

 

https://we.tl/t-gY0X2iynwy

 

 

 

Fra: akasolace <notifications@github.com> 
Sendt: 5. december 2019 08:44
Til: akasolace/HO <HO@noreply.github.com>
Cc: cheilson <kejle@1145.dk>; Mention <mention@noreply.github.com>
Emne: Re: [akasolace/HO] [eBUG] Faulty ratings in HO (#292)

 

@pierpaolocira <https://github.com/pierpaolocira>  you need to select the new match order interface in HT preference.

However, you can't replicate HT values on your side so you will have to rely on @cheilson <https://github.com/cheilson>  inputs. The idea is to see what is wrong with his HO that gives apparently values very off from HT. I thought its FAKTOREN table was corrupted but apparently resetting the coefficients does not fix the issue which is really weired.

**Comment by pierpaolocira** [comment] 2019-12-08 13:08
@akasolace I'm sorry but I have too much work and I cannot deal with this in those days.

@cheilson as a personal suggestion, if you prefer to reply via email, can you please remove the quote of previous message before sending the new one. I know it's not your fault, and there should be an incompaitbility between your email client and github... but the discussion on the website is getting unreadable. ;)

**Comment by akasolace** [comment] 2019-12-08 18:31
@pierpaolocira ok np I will have a look whenever I can

**Comment by akasolace** [comment] 2019-12-16 19:16
@cheilson I was about to look at your issue, but the transfer has been canceled. 
Can I ask you to share it once more.

from the look of it It is clearly your factors which are broken. 
I understand that when you reset them it fixed the issue but at some point the error is coming back, correct?  Have you been using the beta at some point? Did you upgraded straight from 1.437? 
Do you know what steps make the error to come back? 
@wsbrenk it might be similar to the issue you experience, no ?

**Comment by cheilson** [comment] 2019-12-16 20:49
I hope its these two files. https://we.tl/t-EKlKjRKljq

It didn't fix the issue when reset.
At some point it suddenly worked, and then later it didn't work again.
Its a new clean install, I just imported my old HRF files.

I Cannot reproduce how to fix it, havent used HO too much since.

**Comment by akasolace** [comment] 2019-12-17 17:06
@cheilson  I simply opened the database and the lineup was there but ratings were good.
I cant reproduce the error ...

**Comment by wsbrenk** [comment] 2019-12-29 10:10
today i found a possible cause of this error. if the lineup will be switched, there is no reset of the starting times of the players. if in the previous lineup the player is object of a substitution (in my case starting in minute 90), this minute is still in place even if the player starts in minute 0.

**Comment by akasolace** [comment] 2019-12-29 17:03
>  if the lineup will be switched

what do you mean by 'switched' ?

possibly closed by 1e3660419c3046ed687c2453ad7f2e4c0d173f91

**Closed** 2019-12-29 17:03 UTC
Labels: reso: info needed, status: volunteer required

**Comment by wsbrenk** [comment] 2019-12-29 18:09
what i did on my feature branch was to select "previous lineup" in lineup assistant panel. but you could also change the lineup manually. the starting time is set by the current lineup (friendly on tuesday) and will never be changed.

**Comment by akasolace** [comment] 2019-12-30 07:49
@wsbrenk ok
