### ISSUE TITLE
[BUG] java.lang.RuntimeException: com.kitfox.svg.SVGException: java.lang.IllegalArgumentException: User must specify at least 2 colors

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#747] opened 2020-10-23 09:58 UTC
**Describe the bug**
While trying to run a second portable version on my laptop a RuntimeException occures while moving cursor.

**To Reproduce**
It occures while opening HO! 4.0
see attachment 

**Screenshots**
[HO 40 runtimeError.txt](https://github.com/akasolace/HO/files/5428749/HO.40.runtimeError.txt)

**Platform information:**
 - OS: [Windows 10 pro (10.0.19041 Build 19041)]
 - Version (HO-4.0.1.3266-portable-win-BETA-JRE)

**Additional context**

**Comment by akasolace** [comment] 2020-10-23 10:06
you are launching twice the same portable version or do you have 2 different HO versions ?

**Comment by johari75** [comment] 2020-10-23 10:08
twice the same version.

**Comment by johari75** [comment] 2020-10-23 11:01
@akasolace  Now the same problem occures while starting HO for my team

**Comment by johari75** [comment] 2020-10-23 12:52
@akasolace After HO restart it worked for my team again. 
Very strange.

**Comment by weisJ** [comment] 2020-10-23 23:03
This was caused by an issue in darklaf which should be fixed now (don't know the specific version. Maybe `2.4.7` or so).
It is caused by the compact definition option for dynamic svg colours darklaf offers
i.e. instead of
````
<linearGradient id="jerseyColor">
    <stop offset="0" stop-color="#FF0000"/>
    <stop offset="1" stop-color="#FF0000"/>
</linearGradient>
````
one can only specify
````
<linearGradient id="jerseyColor">
    <stop offset="0" stop-color="#FF0000"/>
</linearGradient>
````
The svg rendering library used by darklaf isn't happy though if the aren't at least 2 stop definitions.
Even though updating to the latest darklaf version should fix the issue I would recommend to update the definitions to always include 2 stops.

**Comment by akasolace** [comment] 2020-10-26 16:17
@weisJ we are using 2.4.5.   This issue has been reported only once and I personally never experienced it. I would apply the fix you suggested. Thank you

**Comment by johari75** [comment] 2020-10-27 10:26
Is there anything I can do to support you or to test your solution anyhow?

**Comment by akasolace** [comment] 2020-10-27 11:41
@johari75 you should be able to test with the next beta ...

**Comment by johari75** [comment] 2020-10-28 08:13
@akasolace great. Do you have an approximate date for next beta release?

**Closed** 2020-10-28 09:17 UTC
Labels: type: bug

**Comment by akasolace** [comment] 2020-10-28 09:22
> @akasolace great. Do you have an approximate date for next beta release?

we still have some open tickets, but hopefully by the end of next week
