### ISSUE TITLE
In player overview and in line up, mark player played in week

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#44] opened 2018-12-15 09:40 UTC
new feature

**Comment by akasolace** [comment] 2018-12-15 11:10
are you imagining something like a new column
   - player on the linup for next amical (resp cup, league) has a faded amical (resp cup, league) icon
   -  player who played last amical (resp cup)  has a plain amical (resp cup) icon

is it correct ?

**Comment by mistermax80** [comment] 2018-12-15 12:07
Yes, You  read me in my mind

**Comment by akasolace** [comment] 2019-03-13 21:14
@yaute74 I hope you are doing well. 
In case you want to stay in touch with HO, I would suggest that bug to you.
Next release not expected before July so really no pressure here, I just want to make sure you stay active and we are not loosing you :-)

**Comment by akasolace** [comment] 2019-03-21 10:26
I guess the difficulty might be to handle game since last training as it differs per region.
I am not sure if this information is already available in HO and what is available though CHPP....

**Comment by brokenelevator** [comment] 2019-03-23 16:48
What if we just add 'week start' information to leagues(countries) table? I think my updates are Friday after 2 AM. If we gather all the times/dates we can just count if player played a (relevant) game (and position) since last 'week start'. We can even show what effectiveness (full/half/whatnot) and what position/skill.

I don't think the information is available in HO and don't know if it is in CHPP.
On second thought, HO knows who to give training update. If it didn't we wouldn't have subskill updates. So maybe just use the knowledge to inform us in advance. Unless it 'subskill recalculates' it.

I guess this needs some research.

**Comment by akasolace** [comment] 2019-03-24 19:27
@brokenelevator I was thinking it might be saved in the database because in my memory HO was increasing decimal of trained skills, however when I just checked I realized I have lost all my decimal information just as @mistermax80  reported a while ago.

**Comment by akasolace** [comment] 2019-03-24 19:34
@brokenelevator otherwise I just checked and that information is available via CHPP

```
TrainingDate : DateTime
The date and time when the next training update will start in this league.
```

**Comment by akasolace** [comment] 2019-03-24 19:39
@brokenelevator in HO the info is in table XTRADATA
column TRAINING DATE

**Comment by akasolace** [comment] 2019-03-24 19:40
but I also just notice my table TRAINING is empty
I guess it a bug ..

**Comment by brokenelevator** [comment] 2019-03-26 12:28
It appears that we have the data so this should not be much of a problem to show the information in advance.

About the sub skills they must be retained somewhere.
I have sub skills. Both in HO and DB.
In `SPIELER` under `SUBTORWART`, `SUBVERTEIDIGUNG`, `SUBSPIELAUFBAU`, `SUBFLUEGEL`, `SUBTORSCHUSS`, `SUBPASSPIEL` and `SUBSTANDARDS`.

> but I also just notice my table TRAINING is empty

Mine is not, but the data is old... last entry is from around April 2016.
I could be a bug but the column may also be legacy. No longer used but not removed.

**Comment by yaute74** [comment] 2019-04-05 19:57
> @yaute74 I hope you are doing well.
> In case you want to stay in touch with HO, I would suggest that bug to you.
> Next release not expected before July so really no pressure here, I just want to make sure you stay active and we are not loosing you :-)

@akasolace ok I will study it next week

**Comment by akasolace** [comment] 2019-04-05 21:51
@yaute74 ok cool .. nice to have you back !

**Comment by akasolace** [comment] 2019-05-01 07:00
I will wait for extra testing and feedback [  @DavidatorusF :-) ] before closing the issue.

**Comment by akasolace** [comment] 2019-05-01 15:13
@yaute74 I merged your pull request, I updated from previous dev version to latest one and I got the following error on Launch

```
"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:49900,suspend=y,server=n -javaagent:C:\Users\SABRYC~1\AppData\Local\Temp\groovyHotSwapjars\gragent.jar -javaagent:C:\Users\SABRYC~1\AppData\Local\Temp\captureAgentjars\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_181\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\rt.jar;D:\Perso\Code\HO\out\production\classes;D:\Perso\Code\HO\out\production\resources;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\27.1-jre\e47b59c893079b87743cdcfb6f17ca95c08c592c\guava-27.1-jre.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.jgoodies\jgoodies-looks\2.7.0\7679705b2d036267407138983611a4dd3ec9b72c\jgoodies-looks-2.7.0.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.toedter\jcalendar\1.4\180cf82b37b0c1324e7de33bd0114be7d86678cd\jcalendar-1.4.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\org.scribe\scribe\1.3.0\8a9f92023995a881e97622f82a2dd36d23dda06c\scribe-1.3.0.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\org.hsqldb\hsqldb\2.4.1\9daff99b4fbd6809fd46ab4327650ad00a1be6d4\hsqldb-2.4.1.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.guava\failureaccess\1.0.1\1dcf1de382a0bf95a3d8b0849546c88bac1292c9\failureaccess-1.0.1.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\b421526c5f297295adef1c886e5246c39d4ac629\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\3.0.2\25ea2e8b0c338a877313bd4672d3fe056ea78f0d\jsr305-3.0.2.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-qual\2.5.2\cea74543d5904a30861a61b4643a5f2bb372efc4\checker-qual-2.5.2.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.errorprone\error_prone_annotations\2.2.0\88e3c593e9b3586e1c6177f89267da6fc6986f0c\error_prone_annotations-2.2.0.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.google.j2objc\j2objc-annotations\1.1\976d8d30bebc251db406f2bdb3eb01962b5685b3\j2objc-annotations-1.1.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\org.codehaus.mojo\animal-sniffer-annotations\1.17\f97ce6decaea32b36101e37979f8b647f00681fb\animal-sniffer-annotations-1.17.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\com.jgoodies\jgoodies-common\1.8.1\dffc159cf71bde5dcbb65916305684f6b43d45b1\jgoodies-common-1.8.1.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.4\4216af16d38465bbab0f3dff8efa14204f7a399a\commons-codec-1.4.jar;C:\Users\Sabry CHEIKHROUHOU\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5\lib\idea_rt.jar" core.HO
Connected to the target VM, address: '127.0.0.1:49900', transport: 'socket'
 [Error]   HO: Launched from IDE otherwise there is a bug !
 [Info]    DBUpdater: Development update done, setting db version number from 24 to 24
 [Warning] Lineup: The player id: 422676128 cannot do the substitution
 [Warning] Lineup: The player id: 436891839 cannot do the substitution
 [Info]    HOMainFrame: This is HO! version 0.000 DEV, have fun!
 [Info]    HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 1.8.0_181 (Oracle Corporation)
 [Error]   ExceptionHandler: java.lang.NullPointerException
 [Error]   ExceptionHandler: java.util.Calendar.setTime(Calendar.java:1770)
 [Error]   ExceptionHandler: core.training.TrainingPreviewPlayers.getMatchesForTraining(TrainingPreviewPlayers.java:196)
 [Error]   ExceptionHandler: core.training.TrainingPreviewPlayers.calculateWeeklyTrainingForPlayer(TrainingPreviewPlayers.java:136)
 [Error]   ExceptionHandler: core.training.TrainingPreviewPlayers.getTrainPreviewPlayer(TrainingPreviewPlayers.java:75)
 [Error]   ExceptionHandler: core.gui.comp.entry.SpielerLabelEntry.updateDisplay(SpielerLabelEntry.java:324)
 [Error]   ExceptionHandler: core.gui.comp.entry.SpielerLabelEntry.createComponent(SpielerLabelEntry.java:221)
 [Error]   ExceptionHandler: core.gui.comp.entry.SpielerLabelEntry.<init>(SpielerLabelEntry.java:69)
 [Error]   ExceptionHandler: core.gui.model.UserColumnFactory$14.getTableEntry(UserColumnFactory.java:257)
 [Error]   ExceptionHandler: core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:163)
 [Error]   ExceptionHandler: core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:89)
 [Error]   ExceptionHandler: module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:144)
 [Error]   ExceptionHandler: module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:33)
 [Error]   ExceptionHandler: module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:182)
 [Error]   ExceptionHandler: module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:121)
 [Error]   ExceptionHandler: module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:45)
 [Error]   ExceptionHandler: module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
 [Error]   ExceptionHandler: core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
 [Error]   ExceptionHandler: core.gui.HOMainFrame.initComponents(HOMainFrame.java:483)
 [Error]   ExceptionHandler: core.gui.HOMainFrame.<init>(HOMainFrame.java:176)
 [Error]   ExceptionHandler: core.gui.HOMainFrame.instance(HOMainFrame.java:279)
 [Error]   ExceptionHandler: core.HO$1.run(HO.java:225)
 [Error]   ExceptionHandler: java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
 [Error]   ExceptionHandler: java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
 [Error]   ExceptionHandler: java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 [Error]   ExceptionHandler: java.awt.EventQueue.access$500(EventQueue.java:97)
 [Error]   ExceptionHandler: java.awt.EventQueue$3.run(EventQueue.java:709)
 [Error]   ExceptionHandler: java.awt.EventQueue$3.run(EventQueue.java:703)
 [Error]   ExceptionHandler: java.security.AccessController.doPrivileged(Native Method)
 [Error]   ExceptionHandler: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 [Error]   ExceptionHandler: java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 [Error]   ExceptionHandler: java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by akasolace** [comment] 2019-05-01 15:29
@yaute74 
If I delete db folder and launch new version I have no error message but I can't see the new functionality neither ...

**Comment by yaute74** [comment] 2019-05-01 19:46
@akasolace 
> If I delete db folder and launch new version it works .... looks I can't just copy my old db folder
Yes I made additional test the update is not working
to reproduce: from 1.436 -> update dev channel -> launch HO (error message above is displayed)

What do you have in the table XTRADATA for the field TRAININGDATE (for the last HRF) ?
On my side I have not this exception and the date in the table is correct.

But when I do the update on linux (with channel update) I have this error:
>Started from zip                                                                
Starting HO from ....\n                                                         
Exception in thread "main" java.lang.NoClassDefFoundError: core/HO              
        at HOLauncher.main(HOLauncher.java:28)                                  
Caused by: java.lang.ClassNotFoundException: core.HO                            
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)                                                              
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)                                                           
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)      
        ... 1 more 

>Otherwise, would not it be better to automatically set future training based on latest one (HT behaviour) like this right after update users can see the new functionality, I don'r really see any downside to such behaviour

I am agree, but we shouldn't do it for users who have voluntarily changed it.

**Comment by DavidatorusF** [comment] 2019-05-01 20:33
quick check
tested from the last dev HO2 1075 updated to 1088

![image](https://user-images.githubusercontent.com/45043004/57039985-72303b80-6c5e-11e9-8396-3ce7966d57ba.png)
substitutes is not translated -> poeditor
first row of substitutes : I can't select the same player for different places
second row : good job, work like a charm

notice : was noticed a long time ago... in the right corner, for "style de vie" it's "neutral" till I click on it for get "neutre" (as translated)

use tab "player analysis" block HO... I tryed different thinks... seem I need to kill the process ...

**Comment by akasolace** [comment] 2019-05-01 20:39
@DavidatorusF  is it working for you with update or only with fresh install ?
@yaute74 update is still not working for me with your latest PR

i.e to reproduce, copy db folder to HO2 1088 and launch HO

```
java.lang.NullPointerException
	at java.util.Calendar.setTime(Unknown Source)
	at core.training.TrainingPreviewPlayers.getMatchesForTraining(TrainingPreviewPlayers.java:196)
	at core.training.TrainingPreviewPlayers.calculateWeeklyTrainingForPlayer(TrainingPreviewPlayers.java:136)
	at core.training.TrainingPreviewPlayers.getTrainPreviewPlayer(TrainingPreviewPlayers.java:75)
	at core.gui.comp.entry.SpielerLabelEntry.updateDisplay(SpielerLabelEntry.java:324)
	at core.gui.comp.entry.SpielerLabelEntry.createComponent(SpielerLabelEntry.java:221)
	at core.gui.comp.entry.SpielerLabelEntry.<init>(SpielerLabelEntry.java:69)
	at core.gui.model.UserColumnFactory$14.getTableEntry(UserColumnFactory.java:257)
	at core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:163)
	at core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:89)
	at module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:144)
	at module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:33)
	at module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:182)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:121)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:45)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:483)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:176)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:279)
	at core.HO$1.run(HO.java:225)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by akasolace** [comment] 2019-05-01 20:48
> quick check
> tested from the last dev HO2 1075 updated to 1088
> ubuntu 16.04
> 

> ![image](https://user-images.githubusercontent.com/45043004/57039985-72303b80-6c5e-11e9-8396-3ce7966d57ba.png)
> substitutes is not translated -> poeditor

yes normal translations are lagging

> first row of substitutes : I can't select the same player for different places

arf: it was also the behaviour in previous HO version but it was already incorrect  (bug 1)


> second row : good job, work like a charm

at least a good news ! :-)

> notice : was noticed a long time ago... in the right corner, for "style de vie" it's "neutral" till I click on it for get "neutre" (as translated) 

I guess you mean style de jeu but I got it yes ..   (bug 2)
> 
> use tab "player analysis" block HO... I tryed different thinks... seem I need to kill the process ...
I just fixed this one but havent released it yet  (it was bug #114)

@DavidatorusF  can you open 2 differents bugs ticket for the 2 bugs you reported ?
after that I will delete those comments to not polute this thread.

Thank you for the testing

**Comment by DavidatorusF** [comment] 2019-05-01 20:50
@akasolace tested from the last dev HO2 1075 updated to 1088

no time for test with fresh install or fresh install with old db right now

at restart, seem I have broke my db
I get a warning to update to 1431 ???
![image](https://user-images.githubusercontent.com/45043004/57041199-f46e2f00-6c61-11e9-90a5-394cfeaedab9.png)

**Comment by DavidatorusF** [comment] 2019-05-01 20:56
got my db back... using the forlast one

import my hrf from today... all player are marked null in squad ???

restart HO, my last hrf is take in count as well (it seem)

I go to bed... I will try to do what I can in the next days

**Comment by akasolace** [comment] 2019-05-01 20:59
@yaute74 @DavidatorusF  yes something wrong here

if I summarize

- upgrade DEV -> DEV : works once but corrupt database crash on next restart (tester Davidatorus)
- upgrade stable-> DEV : crash with error message as shown above (tester Akasolace)
- using new from zip -> works well

@yaute74  we dont really care about the path DEV->DEV so we should not worry about this one  but we should fix stable -> DEV

**Comment by akasolace** [comment] 2019-05-01 21:02
> I go to bed... I will try to do what I can in the next days

@DavidatorusF,  I will wait we got this bug closed before building new artefacts.  Until it is done you can open the 2 bugs you reported. Cheers

**Comment by DavidatorusF** [comment] 2019-05-01 21:04
upgrade DEV -> DEV : works once but corrupt database crash on next restart (tester Davidatorus)

no... player analysis breack HO then the db

without use player analysis, restart work well

**Comment by yaute74** [comment] 2019-05-01 21:18
>update is still not working for me with your latest PR

@akasolace my PR was not for your problem (sorry if it was not explicit).

For your problem it's a problem in your table XTRADATA field TRAININGDATE
What do you have inside ?

**Comment by yaute74** [comment] 2019-05-01 21:21
@DavidatorusF can you share the database with the problem ?

**Comment by DavidatorusF** [comment] 2019-05-01 21:27
@yaute74 look at your HT-Mail

**Comment by akasolace** [comment] 2019-05-02 06:23
> > update is still not working for me with your latest PR
> 
> @akasolace my PR was not for your problem (sorry if it was not explicit).
> 
> For your problem it's a problem in your table XTRADATA field TRAININGDATE
> What do you have inside ?

ah ok sorry I misread then. I will check tonight but I believe I might have an issue with that field because as I already reported in my HO I do not have anymore the decimal for my trained player so it might be linked.

**Comment by akasolace** [comment] 2019-05-02 17:11
@yaute74  
XTRADATA field TRAININGDATE: last value 01.02.2019 !

**Comment by akasolace** [comment] 2019-05-02 17:37
@yaute74 @brokenelevator 
ok so I think I fixed it and by the way 2 others related bugs.
I will push later

**Comment by yaute74** [comment] 2019-05-02 18:33
>ok so I think I fixed it and by the way 2 others related bugs.
I will push later

@akasolace  Great  :)

>I get a warning to update to 1431 ???

@DavidatorusF  HO start correctly with your database.
The message "DB is too old. Please update first to HO 1.431" is hard-coded. I think it happened when it cannot get the dbversion so it set version to 0 and display this message.
Do you have the logs corresponding to the message ? or try to reproduce and send the logs ?

I think we can change the message because nobody has a database with a version equal to 0,1,2 or 3!
Something like 'Cannot get dbversion. Do a backup of your log and open an issue. You can try to restart..." or somthing else, what do you think @akasolace  ?

**Comment by akasolace** [comment] 2019-05-02 20:51
> I think we can change the message because nobody has a database with a version equal to 0,1,2 or 3!
Something like 'Cannot get dbversion. Do a backup of your log and open an issue. You can try to restart..." or somthing else, what do you think @akasolace ?

Yes agree the message is currently misleading. A different error message would be more appropriate.

**Comment by akasolace** [comment] 2019-05-02 20:53
> ok so I think I fixed it and by the way 2 others related bugs.
> I will push later
> 
>> @akasolace Great :)

so I fixed so far 3 bugs, now I have my training history which is correct in my db but still no subskills, the calculate subskills does not work for me. Never tried it before. Is it working for you or was it also another known bug ?

**Comment by akasolace** [comment] 2019-05-02 21:13
the bug I experienced was closed by ef27789

**Closed by akasolace** 2019-05-02 21:13 UTC
Labels: effort: unknown, type: feature

**Comment by yaute74** [comment] 2019-05-03 12:33
>so I fixed so far 3 bugs, now I have my training history which is correct in my db but still no subskills, the calculate subskills does not work for me. Never tried it before. Is it working for you or was it also another known bug ?

@akasolace  I will check tonight. I don't check it each week on dev version.

**Comment by yaute74** [comment] 2019-05-03 12:53
>Otherwise, would not it be better to automatically set future training based on latest one (HT behaviour) like this right after update users can see the new functionality, I don'r really see any downside to such behaviour

@akasolace I think it's not necessary to do something because if you set correctly your training it will create new lines, each week, with the same training. Just add a warning in the changelog to inform users that it must set correctly ?

**Comment by akasolace** [comment] 2019-05-03 13:07
> @akasolace I think it's not necessary to do something because if you set correctly your training it will create new lines, each week, with the same training. Just add a warning in the changelog to inform users that it must set correctly ?

in that case should we not put somewhere in the lineup the training assumption, either "Playmaking 100% (10% Stamina)" or "Future training plan not set". Don't you think it would be better? 
If we think it would be a nice addition but it involves too much work we can also open a ticket without milestone and leave it open for the future ...

**Comment by yaute74** [comment] 2019-05-03 18:41
@akasolace in the lineup the blue frame I add indicate the future training position. We can also add text

**Comment by mistermax80** [comment] 2019-05-08 10:42
Hi @yaute74 ,
I would like to know also the players who playing in week in position not trained.

**Comment by yaute74** [comment] 2019-05-08 18:58
@mistermax80 it's what I do at start but I change it because it was not the goal this issue (look on slack the discussion) but of course we can implement it. I think it will be better to create a new issue and w can treat it when training view work fine.

**Comment by mistermax80** [comment] 2019-09-29 21:18
> @mistermax80 it's what I do at start but I change it because it was not the goal this issue (look on slack the discussion) but of course we can implement it. I think it will be better to create a new issue and w can treat it when training view work fine.

@yaute74 What do you mean whe you say "when training view work fine"?

Anyway I created new issue.

**Comment by akasolace** [comment] 2019-09-30 09:17
@mistermax80  I think that at the time @yaute74 was still working on this feature but it is now working fine.
