### ISSUE TITLE
[eBUG] Integrity constraint violation after db migration from v1.434 to v1.436

### ISSUE THREAD

**Issue by cr0ssw1nd** [akasolace/HO#104] opened 2019-03-16 11:13 UTC
After upgrading HO! from v1.434 to 1.436, while step "Initializing database", error occurs:

"Fatal database error. Exiting HO!
You should restore the db-folder from backup or delete that folder."

1. Preparation: Install HO! v1.436, copy db folder from the v1.434 location ("~/.hattrickorganizer") to the appropriate place in v1.436 ("~/.ho")
2. Start HO! v1.436, it will show up after updating database successfully
3. Terminate HO!
4. Start HO! again
4. Error described above occurs

**Platform information:**
 - OS: Linux Mint
 - v18.2, Kernel 4.15.0-46-generic x86_64

Log entry: 
1st run:
18:09:45 [Info]    core.db.DBUpdater: Update done, setting db version number from 20 to 24
18:09:45 [Info]    core.db.DBUpdater: Update done, setting db version number from 20 to 24
18:09:45 [Info]    core.db.DBUpdater: Update done, setting db version number from 20 to 24
18:09:45 [Info]    core.db.DBUpdater: Update done, setting db version number from 20 to 24
18:09:47 [Info]    core.gui.HOMainFrame: This is HO! version 1.436, have fun!
18:09:47 [Info]    core.gui.HOMainFrame: Operating system found: Linux on amd64 (4.15.0-46-generic)
18:09:47 [Info]    core.gui.HOMainFrame: Using java: 1.8.0_191 (Oracle Corporation)

2nd run:
18:28:08 [Error]   core.db.JDBCAdapter: JDBCAdapter.disconnect : java.sql.SQLException: error in script file line: 284730 org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10203 table: USERCONFIGURATION in statement [SHUTDOWN COMPACT]

I sent you the link to the files by HT-Mail. 

Watch the size of database.data from 134mb before 1st run after migration, shrinking to 84mb after terminating HO! and before starting it a 2nd time where the error raises up.

**Comment by brokenelevator** [comment] 2019-03-20 16:33
@akasolace are you the 'you' cr0ssw1nd is refering to? Because I could take care of it but probably need the database to reproduce the issue.

**Comment by akasolace** [comment] 2019-03-21 07:45
@brokenelevator, yes I will share with you the database
I need first to have an updated download link.

**Comment by akasolace** [comment] 2019-03-27 08:19
root error of database corruption was not found, the database was manually fixed by @brokenelevator 
it could be linked to a rare event of shutdown compact signal launched while duplicated indices existed.
in the process of investigating the error some sql fixes were made by brokenelevator and the duplicated indices were removed

**Closed by akasolace** 2019-03-27 08:19 UTC
Labels: effort: unknown, reso: info needed, type: bug
