### ISSUE TITLE
Change Language is not possible

### ISSUE THREAD

**Issue by elmero1** [akasolace/HO#842] opened 2021-01-02 09:03 UTC
It's not possible to change the language. After restart the language is still in English.

**Comment by akasolace** [comment] 2021-01-02 10:39
which language did you try to select ?

**Comment by elmero1** [comment] 2021-01-02 11:50
German.

**Comment by akasolace** [comment] 2021-01-21 07:46
@elmero1 I never heard of such issue. Also I tried to reproduce many time, never could. 
Do you still experience that bug ?   Whic version of HO are you using and on which platform?  Also could you please give a try to the latest development version?

**Comment by akasolace** [comment] 2021-01-29 13:39
@wsbrenk could you reproduce this one ?

**Comment by wsbrenk** [comment] 2021-01-30 10:27
@akasolace with HO 4.1 i did:

* Datei->Einstellungen->Sprache Deutsch->English ->Speichern ->restart HO -> HO display is the english one
* File->Preferences->Language English->Deutsch ->Save ->restart HO -> HO display is the german one

i could not reproduce @elmero1 issue - sorry

**Comment by wsbrenk** [comment] 2021-01-30 10:34
![Translation](https://user-images.githubusercontent.com/11821502/106354005-f1004f80-62ee-11eb-867a-0001cb2f7f53.png)

some german translations are still missing. but i don't think, that could be the reason for this issue!?

**Comment by akasolace** [comment] 2021-02-03 17:46
@elmero1 sorry but this issue has never been reported by someone else and we can't reproduce it. Hence we gonna close it for the time being.

**Closed** 2021-02-03 17:47 UTC
Labels: reso: can't reproduce

**Comment by timeout972** [comment] 2021-12-10 01:42
same problem with French 
File->Preferences->Language English->French ->Save ->restart HO -> HO display is English
Mac OS 12.0.1 HO Version 5.0.3836.2 (5.0.3836.2)
<img width="450" alt="Capture d’écran 2021-12-09 à 21 35 42" src="https://user-images.githubusercontent.com/66527541/145502780-1397bfb8-29b6-42e2-99c0-9b8686d44736.png">
<img width="451" alt="Capture d’écran 2021-12-09 à 21 35 33" src="https://user-images.githubusercontent.com/66527541/145502872-36a058f1-d1f6-4b85-9c30-3b08c2259ac6.png">
<img width="447" alt="Capture d’écran 2021-12-09 à 21 35 23" src="https://user-images.githubusercontent.com/66527541/145502912-6303603b-3fc3-431a-9ec6-46082fc1865c.png">

**Comment by wsbrenk** [comment] 2021-12-20 16:07
can't reproduce this on windows.
