### ISSUE TITLE
[BUG] MacOS trouble with CHPP authorization code

### ISSUE THREAD

**Issue by paulreds** [akasolace/HO#821] opened 2020-12-02 20:56 UTC
**Describe the bug**
Using version 4.1 on my Mac I'need to reinsert CHPP code each time I restart it trying to download .hrf file

**To Reproduce**
1. Go to 'file'
2. Click on 'download'
3. Select dowload in the dialogue window

**Screenshots**
![Schermata 2020-12-02 alle 21 41 12](https://user-images.githubusercontent.com/74708272/100930316-34099680-34e9-11eb-8f3a-d847c79d4ecb.png)

**Platform information:**
 - OS: Mc Os

**Additional context**

**Comment by akasolace** [comment] 2020-12-03 07:36
duplicate of #811

**Comment by tychobrailleur** [comment] 2020-12-05 12:02
Closing as dupe of #811.

**Closed by tychobrailleur** 2020-12-05 12:02 UTC
Labels: reso: duplicate
