### ISSUE TITLE
[eBUG]Exclude Last Lineup not working right

### ISSUE THREAD

**Issue by theobserver** [akasolace/HO#390] opened 2020-02-15 22:43 UTC
Exclude Last Lineup not working right.
- I downloaded last data in HO.
- I tick the checkbox Exclude Last Lineup
- I pressed button Clear Lineup
- I pressed button Start Assistant

and then 3 players from the last lineup appear in the suggested auto lineup.

Then i untick those players from being suggested. I follow the above procedure and again 2 players from last match lineup are suggested from HO assistant.
What am i doing wrong?

Regards.
Nik.

**To Reproduce**
what i describe above.

**Screenshots**

**Platform information:**
 - OS: [Windows]
 - Version (2100)

**Additional context**

**Comment by wsbrenk** [comment] 2020-02-16 08:23
@theobserver have the 3 players been replaced in the previous game? If so, the question is whether this is desired or an error.

**Comment by theobserver** [comment] 2020-02-16 12:25
The 3 players were not replaced in the previous game. Exclude last lineup is used to exclude the previous game players from the assistant results. It is used so the players of the team that were not participating in the previous game can be suggested by the assistant and get training at a friendly game for example...

**Comment by wsbrenk** [comment] 2020-02-16 15:15
@theobserver When I tried to reproduce your error message, I noticed that the assistant has considered a player who was replaced in the last match. The player who replaced this player for only 25 minutes was not considered. even that is not clever, since the replacing player played less minutes than the replaced one and got less training so.

in my test no player was considered who played the last minutes of the previous match. 

question: the 8 other players considered by the automatic assistant are they better than those of your last match? what distinguishes them from the others.

if you want, you could contact me in hattrick (wsbrenk is my manager name, too). then i could try to find out, what might be the reason for that error.

**Comment by theobserver** [comment] 2020-02-17 07:06
I looked more closely the issue.It seems that the same players suggested are not 3 as i said in my original post. They are 5. I do not think that the assistant takes in consideration the previous lineup even if i have ticked the exclude last lineup button.

**Comment by wsbrenk** [comment] 2020-02-20 19:29
in the db table AUFSTELLUNG i found some old hrf imports where the last lineup is missing. normally there are two entries for each hrf. up to now i do not have an idea what is the reason for these missing entries.

**Comment by akasolace** [comment] 2020-02-20 21:01
@wsbrenk if it is too specific and dificult to reproduce we might put this one on hold for the moment

**Comment by wsbrenk** [comment] 2020-02-22 12:52
@theobserver please check if ho shows the correct last lineup
![lastlineup](https://user-images.githubusercontent.com/11821502/75092684-88efa800-557a-11ea-8a9a-7667cccc84a3.jpg)

**Comment by theobserver** [comment] 2020-02-25 17:04
As you can see in the screenshots ho was not showing the correct lineup. It fixed after i downloaded 
![Ho-02](https://user-images.githubusercontent.com/5185594/75269420-894da480-5801-11ea-8744-05e874bcdf37.jpg)
![Ho-01](https://user-images.githubusercontent.com/5185594/75269429-8baffe80-5801-11ea-9aae-4611c54afaf1.jpg)

**Comment by wsbrenk** [comment] 2020-02-26 18:32
when i reimport the hrf file, the missing last lineup is saved correctly.

**Comment by akasolace** [comment] 2020-03-01 10:47
@wsbrenk I am not really following this one ... is this a real issue or should I close it ?

**Comment by theobserver** [comment] 2020-03-01 11:09
As far as i am concerned, it is working ok now for me.
Seems the only instance this problem occurred was when i upgraded to the new HO from the old deprecated one and apart that time it is working ok for me now.

Regards.

**Comment by wsbrenk** [comment] 2020-03-01 12:21
> I am not really following this one ... is this a real issue or should I close it ?

@akasolace i'm not very happy with the workaround waiting for the next import to fix the issue. i would like to investigate for a while what causes the missing last lineups

**Comment by akasolace** [comment] 2020-03-01 13:28
>  i would like to investigate for a while what causes the missing last lineups

I think this could be my fault. At some point I think I removed this and it was reintroduced by a commit made by @tychobrailleur. Maybe someone who used the development version for a while could have encountered that issue

**Comment by wsbrenk** [comment] 2020-03-01 14:28
You could be right. at the moment i don't find any gaps anymore. it seems, that everything has repaired itself. so you could close this ticket.

**Closed** 2020-03-01 15:10 UTC
Labels: effort: unknown, reso: info needed
