### ISSUE TITLE
[BUG] no subskill for Set Pieces in tabs Training and Squad

### ISSUE THREAD

**Issue by wwn** [akasolace/HO#836] opened 2020-12-22 18:37 UTC
Current state:
On tab Training in the top right corner the trainings are set well: week 9 Crossing(Winger), week 10...13 Set Pieces.

- In the left big pane the green/red bars are in column Winger.
- On tab Squad there are no fraction numbers in column Set Pieces. In column Winger are some.

Desired state:

- On tab training show green/red bars on the left big pane for Set Pieces as well.
- On tab Squad show fraction numbers in columns Set Pieces as well.

I already reloaded all games and pressed the "Subskill recalculation" button.

HO 4.1.

screenshots: https://photos.app.goo.gl/sLFf64x22wAKTDy4A

**Comment by akasolace** [comment] 2021-01-21 07:50
@wwn could you please test if you still have this issue on latest development version ? (5.0 DEV)

**Comment by wwn** [comment] 2021-01-21 11:10
gonna give my best, maybe eo week

**Comment by akasolace** [comment] 2021-01-21 12:24
ok great ..

**Comment by wwn** [comment] 2021-01-23 09:10
did on your master r.0.0 smthg, last commit is:
commit 060cab8458fad56e9c6f797b2e267f91ce1d567f
Author: akasolace <thisiakasolace@gmail.com>
Date:   Thu Jan 21 22:45:19 2021 +0100
fixes League module, when alltid return different array size for statistics

bug seams to remain open: no fractural digits in SP in Squad and no bars SP in Training

**Comment by wsbrenk** [comment] 2021-01-25 18:12
I'm afraid that's intentional. when HO see's an complete skillup in the Hattrick-Downloads, it reset it's own subskill calculations to 0. this is very likely if set pieces is trained.

**Comment by akasolace** [comment] 2021-02-01 16:15
duplicate of #795

**Closed by akasolace** 2021-02-01 16:15 UTC
Labels: reso: duplicate, scope: training, status: needs test
