### ISSUE TITLE
[eBUG] training forecast displaying wrong skillups

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#368] opened 2020-01-29 12:33 UTC
in this example my player didn't skill up in week 73,8, but will hopefully skill up in 3 weeks to worldclass:

![trainingsprognosebug](https://user-images.githubusercontent.com/11821502/73357106-0259ea80-429c-11ea-8f8a-c5bf493d6506.jpg)

the skillup in week 73,8 was the skillup to fantastic (12). i think all historical skillup values are one too large.

**Comment by wsbrenk** [comment] 2020-01-29 14:03
found the reason, i'm working on the solution.

**Comment by wsbrenk** [comment] 2020-01-29 17:35
![trainingsprognose](https://user-images.githubusercontent.com/11821502/73381377-e5d2a800-42c5-11ea-82d9-3c53c322f1b5.jpg)
- the bug is fixed
- column Age added
- tooltip showing training date for future trainings too

**Comment by wsbrenk** [comment] 2020-01-29 17:47
@akasolace the last merges from master branch make some problem:

Build file 'C:\Users\wolfgang\Documents\HO\build.gradle' line: 560

A problem occurred evaluating root project 'HO'.
> Could not get unknown property 'GITHUB_TOKEN' for object of type com.github.breadmoirai.githubreleaseplugin.GithubReleaseExtension.


have to go back to an old commit of build.gradle

**Comment by akasolace** [comment] 2020-01-29 19:00
@wsbrenk this is strange I can't reproduce

> found the reason, i'm working on the solution.

who was affected ? which player ?

**Comment by akasolace** [comment] 2020-01-29 19:02
sorry I found some players affected

**Comment by akasolace** [comment] 2020-01-29 19:05
should be closed by #369
I will test before closing

**Closed** 2020-02-02 11:03 UTC
Labels: status: needs test
