### ISSUE TITLE
[eBUG]Catch error when using TeamAnalyzer while team is playing a game

### ISSUE THREAD

**Issue by cheilson** [akasolace/HO#291] opened 2019-11-24 12:29 UTC
I get a java error when i press update in TeamAnalyzer

**To Reproduce**
1. Go to TeamAnalyzer
2. Select next League opponent
3. Press update'
4. Java error:

java.lang.NullPointerException
	at module.teamAnalyzer.ht.HattrickManager.getValue(HattrickManager.java:192)
	at module.teamAnalyzer.ht.HattrickManager.getIntValue(HattrickManager.java:179)
	at module.teamAnalyzer.ht.HattrickManager.downloadPlayers(HattrickManager.java:118)
	at module.teamAnalyzer.ui.FilterPanel$3.actionPerformed(FilterPanel.java:179)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Platform information:**
 - OS: [Windows10]
 - Version (2.0 r1414)

**Additional context**
My opponent is playing right now, I will see if I can reproduce after the macth.

**Comment by cheilson** [comment] 2019-11-24 13:33
No error after the match. Looks like it has something to do with the team playing.

**Comment by akasolace** [comment] 2019-12-11 13:28
maybe we can try to catch the error and either get around it or display a more appropriate error message like "not possible to fetch data at the moment because this team is currently playing a game"

**Comment by wsbrenk** [comment] 2019-12-30 14:24
@akasolace this fits my feature ticket #299. Tomorrow there will be a friendly game where I might be able to reproduce that. I don't feel like New Year's Eve right now: cough, sore throat and no voice

**Comment by akasolace** [comment] 2019-12-30 14:28
@wsbrenk tbh I don't understand the link between this one and #299 but glad that you can look at it...
Also wish you a nice recovery !

**Comment by wsbrenk** [comment] 2019-12-30 14:46
this is because i will first give the team analyzer a chance to implement the special events prediction. i hope that i will have a very first scetch in a few days now.

**Comment by wsbrenk** [comment] 2019-12-31 18:56
could reproduce the error. the difference in the returned xml concerns the cards and injury elements:

not during matches:
        <Cards>0</Cards>
        <InjuryLevel>-1</InjuryLevel>

during match:
	<Cards></Cards>
        <InjuryLevel></InjuryLevel>

**Comment by akasolace** [comment] 2020-01-02 07:20
closed by 2f05bbb

**Closed by akasolace** 2020-01-02 07:20 UTC
Labels: effort: low, status: volunteer required, type: enhancement
