### ISSUE TITLE
[BUG] IFA logo

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#695] opened 2020-09-17 15:13 UTC
**Describe the bug**
12*12= 144... we have 145 flags now

we can adjust the number of flag per line till 12
but we can show only 12 lines, then, now, miss a flag on the logo

we need more lines

**To Reproduce**
1. Go to 'IFA'
2. Use logo creator
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/93490416-bdf18c80-f908-11ea-9f8e-f00fd3c08fa1.png)
seem it miss Zambia at the end

**Comment by akasolace** [comment] 2020-09-20 14:38
please test again as I can't reproduce this one ...

**Comment by DavidatorusF** [comment] 2020-09-20 18:01
@akasolace no more problem on HO4 r3173
I think it was solved in the same time as #694

**Comment by akasolace** [comment] 2020-09-21 08:29
ok cool I close this one then ....

**Closed by akasolace** 2020-09-21 08:29 UTC
Labels: reso: invalid
