### ISSUE TITLE
[BUG] error for users using fatcow icons 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#572] opened 2020-06-13 18:10 UTC
**Describe the bug**
As reported by davidatorus,  upgrade to 4.0 fails for users using fatcows : icons removal should be treated !

**Comment by akasolace** [comment] 2020-06-16 06:40
hello @tychobrailleur  I think this could be treated as part of darklaf light/dark icons ... what do you think?

**Comment by tychobrailleur** [comment] 2020-06-16 16:20
Sorry, @akasolace would you have more context on this?  Where are the fatcow icons used?  It sounds like their usage is platform-dependent? And what is the error encountered?

**Comment by akasolace** [comment] 2020-06-16 16:32
@tychobrailleur actually until now this was an additional set of icons available in /themes.
I removed those extra icons as they were unmaintained (lots of icons were missing) and I don't think we have the resources to offer this. To my surprise at least one user was still using those icons despite having a terrible experience. Hence he encountered an error while testing 4.0.  I think this is a very easy one to fix and I could do it (especially I created the issue) but I thought it could make more sense if you take care of it as if I understand correctly at some point you will introduce dark icons (with community help). Hence it is best if you look after those icons/themes related issues. Does it make sense to you? Is that ok?

**Comment by tychobrailleur** [comment] 2020-06-16 16:43
> Hence it is best if you look after those icons/themes related issues. Does it make sense to you? Is that ok?

@yaute74 is the icon virtuoso, so I am happy to look into this, with his help (& the community's)! ;-)

I still don't understand where those icons were used, though: 

> To my surprise at least one user was still using those icons despite having a terrible experience.

Where are these icons being configured?  I have never come across a place where you could select your own icons, is it in the old themes formerly loaded through a zip file?

**Comment by akasolace** [comment] 2020-06-16 19:07
yes. I think (never used it) the icons were unziped and used instead of default one. @DavidatorusF could maybe tell us more about it ... possibly he was the only user of those icons ;-)

**Comment by yaute74** [comment] 2020-06-16 19:17
@akasolace so maybe we will have a problem, no ? if we rename the files (.png -> .svg) ?
And think it will not work as now we use SVG icons.

**Comment by akasolace** [comment] 2020-06-16 20:12
you mean fatcow? but we are dropping it .... or is it something else?

**Comment by yaute74** [comment] 2020-06-16 20:36
ok great, I misunderstand

**Comment by weisJ** [comment] 2020-06-17 16:50
If you choose to fully move to dark/light icons I would be happy to help you migrate them. I have seen that you are already using some svg icons. It should be noted that painting the `SVGIcon` directly provided by svgSalamander is rather slow. I would advise to use
````java
IconLoader.get().getIcon(path, width, height);
ˋˋˋ
instead. It automatically handles caching and provides faster painting speeds as well as lazy loading. This way you also don’t have to worry about the implementation of the icon.

**Comment by akasolace** [comment] 2020-06-17 18:23
Hi @weisJ, thank you for proposing your help ... it is not a topic I am directly involved with but I am sure @tychobrailleur will appreciate this :-)

**Comment by tychobrailleur** [comment] 2020-06-21 11:54
I am working on removing the player status colours to finally close this one out, and I am wondering if we should totally remove the colours: in Lineup we do need to know the status of the player (injured, suspended, etc.), and we can hardly add extra icons in the player position view, so wondering if we should not keep colours at least there?  WDYT, @akasolace @wsbrenk @yaute74 ?

**Comment by akasolace** [comment] 2020-06-21 13:55
@tychobrailleur good point that we need that information in Lineup view .... maybe we can stick the status icons in there ... in small next to the name ... maybe we can remove the trikot there to make some space (it is some work I agree)

**Comment by tychobrailleur** [comment] 2020-07-12 10:07
This one should be fixed now that the old theming has been removed.

**Comment by akasolace** [comment] 2020-07-13 06:12
@tychobrailleur I am reopening it as I am not sure this one has been closed really. 
I will do some tests first ....

**Comment by akasolace** [comment] 2020-07-17 13:28
@tychobrailleur I tested this one with @DavidatorusF db, the good thing is that it does not throws anymore an error because of fatcows icons but I just realized there are still some player colors.

Actually I do not see at all what was liste in #619     any idea ? 

![image](https://user-images.githubusercontent.com/1136496/87791141-18f00000-c842-11ea-8567-150aacbb7266.png)


![image](https://user-images.githubusercontent.com/1136496/87791025-d9c1af00-c841-11ea-817e-a858c6ac7de1.png)

![image](https://user-images.githubusercontent.com/1136496/87791058-ee05ac00-c841-11ea-8c16-1e62cf9543f9.png)

**Comment by tychobrailleur** [comment] 2020-07-17 17:52
> Actually I do not see at all what was liste in #619 any idea ?

Yes, it looks like e2772ea5e50d38ae27499945304f535f484165ed reverted those changes.

**Comment by wsbrenk** [comment] 2020-07-17 20:33
@tychobrailleur feel free to revert the revert again. but there was a npe i send on 28th june on slack. we thought that it could be introduced by the mentioned commit.

**Comment by tychobrailleur** [comment] 2020-07-17 21:16
> @tychobrailleur feel free to revert the revert again. but there was a npe i send on 28th june on slack. we thought that it could be introduced by the mentioned commit.

No worries.  (=

The NPE was caused by a change around groups, if I remember correctly. I'll have a look tomorrow.

**Closed** 2020-07-27 19:57 UTC
Labels: status: needs test, type: regression
