### ISSUE TITLE
[eBUG] Loading issue  Matches and Matches Analyzer

### ISSUE THREAD

**Issue by Dillotu** [akasolace/HO#471] opened 2020-04-28 19:29 UTC
Hi everyone

Thanks for the new 3.0 beta I love the new League details

I have an issue with the tabs Matches and Matches Analyzer it takes from 3 to 4 minutes to load and during this time HO is stuck. 

**To Reproduce**
As requested I attached my db.  (it looks to big to be attached here I'm going to share in google drive )

**Platform information:**
 - OS: W10
 - Version all version I copy the db in the new version.  I'm testing all the version available at the moment 

**Additional context**
Other feedback (I don't know if they are related to the db)
- Report match is empty and hilight report 0-0 in all my matches.
- In the 2.x and 3.x versions the module special event is empy , events perfect visible in 1.437

I have started with the version1.437 at the end of July 2017.
I also have all the .hrf but unfortunately I can't import them for some I get the error "null" I attach if you can look at them.

[hrf.zip](https://github.com/akasolace/HO/files/4548016/hrf.zip)
Db
https://drive.google.com/file/d/1WiCE1nMfSz9e8shPNp5J7HzFw9v3qVL9/view?usp=sharing

Thanks

**Comment by tychobrailleur** [comment] 2020-04-28 22:15
The DB version is 300 (LastConfUpdate = 1.436)
When getting to the Matches tab, there are lots of errors in the logs like:

```
 [Error]   JDBCAdapter: JDBCAdapter.executeUpdate : java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: EVENT_INDEX
Statement: INSERT INTO MATCHHIGHLIGHTS ( MatchId, Minute, EVENT_INDEX, SpielerId, SpielerName, TeamId, MATCH_EVENT_ID, SpielerHeim, GehilfeID, GehilfeName, GehilfeHeim, INJURY_TYPE, EventText ) VALUES (658073911, 54, 25, 430929098, 'Daniel Sviland', 279992, 181, false, 374000310, 'Hannes Ahlgren', true, 0, 'Dopo 54 minuti ci si mette la sfortuna a peggiorare la situazione dei padroni di casa! Il rinvio del portiere colpisce il tacco del suo compagno! La palla si impenna e cade proprio al centro dell#area di rigore dove <FONT COLOR=#990000#><B>Daniel Sviland</B></FONT> si era attardato a legarsi le scarpe e dove incredulo mette a segno a porta vuota il gol che aumenta il vantaggio degli ospiti. Incredibile.') 
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: EVENT_INDEX
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)

```

and 
```
 [Error]   JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: EVENT_INDEX
Statement: SELECT * FROM MATCHHIGHLIGHTS WHERE MatchId=607353009 ORDER BY EVENT_INDEX, Minute
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: EVENT_INDEX
```
`EVENT_INDEX` is missing from `MATCHHIGHLIGHTS`, but it contains the `MATCH_EVENT_ID` column, so this logic in `updateDBv26` would not have executed:

```
if (!columnExistsInTable("MATCH_EVENT_ID", MatchHighlightsTable.TABLENAME)) {
			try {
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN MATCH_EVENT_ID INTEGER");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN EVENT_INDEX INTEGER");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN INJURY_TYPE TINYINT");
				m_clJDBCAdapter.executeUpdate("UPDATE MATCHHIGHLIGHTS SET MATCH_EVENT_ID = (TYP * 100) + SUBTYP WHERE MATCH_EVENT_ID IS NULL");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS DROP HEIMTORE");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS DROP GASTTORE");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS DROP TYP");
				m_clJDBCAdapter.executeUpdate("ALTER TABLE MATCHHIGHLIGHTS DROP SUBTYP");
			}
			catch (Exception e){
				HOLogger.instance().error(DBUpdater.class,	"DB Corrupted !! Updating to 2.1, MATCH_EVENT_ID column missing in MATCHHIGHLIGHTS and creation not possible !!");
			}
		}
```

**Comment by tychobrailleur** [comment] 2020-04-28 23:13
Once the issues in the db are fixed, the slowness is indeed massive in `SpielePanel`: when ` MatchesTable(UserParameter.instance().spieleFilter)` is called, and even worse `MatchesOverviewTable(UserParameter.instance().spieleFilter)`

Tracing down, it seems to come from `MatchesOverviewQuery#setMatchesOverviewRow` called multiple times over 6.9k matches (which isn't that big...).  I'll investigate how to optimise.

**Comment by tychobrailleur** [comment] 2020-04-29 07:24
I have added two indices to the database, and this drastically sped up the loading of the Matches tab.  It takes 10–15s to load the tab (as opposed to 4–5 min before) now, I'll see if I can improve further.

@Dillotu has this tab always been this slow to load?  Or is it with the new version?  Also, I am noticing it takes an awfully long time to exit HO, is that also the case for you?

**Comment by akasolace** [comment] 2020-04-29 07:30
@tychobrailleur  thanks for looking into it   ... I don't understand how the db could have had "MATCH_EVENT_ID" and not "EVENT_INDEX".... you have any clue ?

**Comment by akasolace** [comment] 2020-04-29 07:31
@Dillotu you upgraded from 1.437 to 3.0 directly ?

**Comment by tychobrailleur** [comment] 2020-04-29 07:54
> @tychobrailleur thanks for looking into it ... I don't understand how the db could have had "MATCH_EVENT_ID" and not "EVENT_INDEX".... you have any clue ?

Yeah, it's an odd one, but it could be due to the history of the DBUpdater changes, and which successive versions of HO Dillotu used.

**Comment by Dillotu** [comment] 2020-04-29 08:06
Hey Guys 

Thank you of you job on the db.

If I'm not wrong the first version used was the 1.436 then I only copied the previous DB in the new version.  I'm using the same DB in the 1.437, 2,x , 3.x.

**Comment by tychobrailleur** [comment] 2020-04-29 20:39
I have got great results for the Matches tab now, it now loads in a few seconds.

@akasolace This requires db updates that should be executed on top of 3.0.0 changes.   How do you suggest to proceed for versioning?  For now I set `DBVersion` to 3.0.1, and [execute updates](https://github.com/tychobrailleur/HO/commit/b07969f7987e3f56c82473595ddcec67c00e9fd1#diff-be5eddbfd52e7bbe49a040ee766f288eR102).  I wrote those statements in a way that they can be run again without error.

**Comment by akasolace** [comment] 2020-04-30 08:00
> For now I set DBVersion to 3.0.1  

yes I think this make sense for versioning as a patch for 3.0

> I am now looking into those empty highlights

you refer to this  ?

> EVENT_INDEX is missing from MATCHHIGHLIGHTS, but it contains the MATCH_EVENT_ID column,

**Comment by tychobrailleur** [comment] 2020-04-30 08:56
I am referring to this in Dillotu's bug report:

> Report match is empty and hilight report 0-0 in all my matches.

**Comment by akasolace** [comment] 2020-04-30 09:01
> I am referring to this in Dillotu's bug report:
> 
> > Report match is empty and hilight report 0-0 in all my matches.

for this  is it true also for recently downloaded game or only for old ones ?

**Comment by tychobrailleur** [comment] 2020-04-30 18:10
> > I am referring to this in Dillotu's bug report:
> > > Report match is empty and hilight report 0-0 in all my matches.
> 
> for this is it true also for recently downloaded game or only for old ones ? For old one it is normal ... normally if you select it and redownload it it fixes this ...

Hmmm, ok.  I think right this doesn't work because of the old non-nullable columns still lying around (`GASTTORE` / `HEIMTORE`), so I'll fix that.  The db has nearly 7,000 matches though – what's the best to download them all?

Re. the slow shutdown, this is caused by a call to `SHUTDOWN COMPACT` which takes a long time.  I was toying with the idea of changing this to `SHUTDOWN` (see [manual](http://www.hsqldb.org/doc/guide/management-chapt.html#mtc_system_operations)), but I am nervous about the impact, so we may just have to live with it.

**Comment by akasolace** [comment] 2020-04-30 20:33
> what's the best to download them all?

I won't do that really,  if he needs to look at a match report of an old game he can just redownload it on demand...

> Re. the slow shutdown, this is caused by a call to SHUTDOWN COMPACT which takes a long time. I was toying with the idea of changing this to SHUTDOWN (see manual), but I am nervous about the impact, so we may just have to live with it.

I would also be tempted to do a normal shutdown,   not sure what is the benefice of compact, what is the size of its database, mine is less than a MB ..

**Comment by wsbrenk** [comment] 2020-05-01 07:59
@tychobrailleur i think you have to add your improvements not only to DbUpdater but also to the creation of the database tables in the corresponding Table classes (MatchesKurzInfoTable, ...), isn't ist?

**Comment by tychobrailleur** [comment] 2020-05-01 08:50
> @tychobrailleur i think you have to add your improvements not only to DbUpdater but also to the creation of the database tables in the corresponding Table classes (MatchesKurzInfoTable, ...), isn't it?

Ah yes, you're right.  Good catch, thanks a lot!

**Comment by akasolace** [comment] 2020-05-01 19:33
@tychobrailleur I think we can close this one, right ?

**Comment by tychobrailleur** [comment] 2020-05-02 08:55
I am closing this one:
- Matches tab should load much faster in the next release,
- Shutdown should also be fast,
- Matches Analyser will be removed,
- For missing highlights, as per @akasolace , matches need to be downloaded again as needed.

Thanks for sharing your db @Dillotu , that was really helpful!

**Closed by tychobrailleur** 2020-05-02 08:55 UTC
Labels: type: bug

**Comment by Dillotu** [comment] 2020-05-02 10:15
> 
> 
> I am closing this one:
> 
>     * Matches tab should load much faster in the next release,
> 
>     * Shutdown should also be fast,
> 
>     * Matches Analyser will be removed,
> 
>     * For missing highlights, as per @akasolace , matches need to be downloaded again as needed.
> 
> 
> Thanks for sharing your db @Dillotu , that was really helpful!

Thank you for you time 

Looking forward to the new version!
