### ISSUE TITLE
various amounts are again in Arabic script ;)

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1622] opened 2022-08-07 15:30 UTC
I open it again - various amounts are again in Arabic script in HO 6.0 ;)

_Originally posted by @peppermil in https://github.com/akasolace/HO/issues/1101#issuecomment-1207431432_

**Comment by wsbrenk** [comment] 2022-08-07 18:28
@peppermil could you please check the file users.json (should be in %APPDATA%HO). The first team listed in this file should be your home team (CH?!).

**Comment by peppermil** [comment] 2022-08-07 21:35
this is the content of the usern.json file:

[
  {
    "teamName": "Lozärner Löwen 04",
    "dbName": "db",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "Lucerne Lions 13",
    "dbName": "db2",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "Lucerne Lions 20",
    "dbName": "db3",
    "backupLevel": 3,
    "isNtTeam": false
  }
]

**Comment by wsbrenk** [comment] 2022-08-08 21:07
i can reproduce it, but i don't know the reason yet.

but if i download data and restartet once the correct speech is loaded.

**Comment by peppermil** [comment] 2022-08-12 10:38
it seems to work now, since I downloaded the data again and restarted HO the correct numbers (language) were loaded.

**Comment by peppermil** [comment] 2022-12-26 11:15
In beta version 6.2 (build 408), salary and average salary are again in Arabic characters.
For the team in Switzerland and Belize, the salaries are correct in CHF.

**Comment by wsbrenk** [comment] 2022-12-26 13:07
@peppermil do you have a log file from this session you can provide? Or better yet, the backup of your database, which I could try to reproduce that with.

**Comment by peppermil** [comment] 2022-12-29 07:21
Hi wsbrenk
thx - i have both - log with many errors
[LL13_HO-2022-12-29.log](https://github.com/akasolace/HO/files/10318088/LL13_HO-2022-12-29.log)
[db_Lucerne Lions 13-2022-12-29.zip](https://github.com/akasolace/HO/files/10318090/db_Lucerne.Lions.13-2022-12-29.zip)

**Comment by wsbrenk** [comment] 2022-12-29 10:43
table HT_WORLDETAILS is empty => league id was not determined

fix this by using initial league list (WorldDetailLeague.allLeagues) if not available in database

**Comment by wsbrenk** [comment] 2022-12-29 13:30
@peppermil let's wait for the review of @tychobrailleur  - then it will be part of the new 7.0-dev version. if you want to test it, please don't do it without backups of your current installation and database files.

**Closed** 2023-01-19 17:33 UTC
Labels: status: needs test
