### ISSUE TITLE
[eBUG] DEV teamanalyser with many stars / player evaluation number

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#184] opened 2019-07-28 12:14 UTC
**Describe the bug**
on teamanalyser, we still see stars... with many stars according to the number with hundreds for player evaluations.. I though you had to divise them by ten for be according with those from foxtrick

**To Reproduce**
1. Go to 'teamanalyser'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/62006510-8abacf80-b141-11e9-9442-aa3e9bb10cd1.png)

**Platform information:**
 - OS: [Linux]
 - Version (Ubuntu 16.04)

**Comment by DavidatorusF** [comment] 2019-07-28 13:01
here is our actual player evaluation
![image](https://user-images.githubusercontent.com/45043004/62006974-3109d380-b148-11e9-8cb4-ac41262bede8.png)
I really think we have to divide them per ten for be according with those from foxtrick and not make users in trouble

once divided, maybe can we let the stars on teamanalyser... I let you know... you're the developer ^^

**Comment by akasolace** [comment] 2019-08-05 21:58
@DavidatorusF I thought I already divide it by 10. 
Are the screenshot made with latest DEV ?

**Comment by DavidatorusF** [comment] 2019-08-06 20:34
@akasolace 2.0 r1273

**Comment by akasolace** [comment] 2019-08-07 10:47
@DavidatorusF  ok I will look at this one when I am back from my hollidays

**Comment by akasolace** [comment] 2019-08-14 19:07
@DavidatorusF  I can't reproduce it.
I think you simply need to do preference -> reset formula and it should be ok.
I close it at the moment, if you think the bug really exist please reopen it .

**Closed by akasolace** 2019-08-14 19:07 UTC

**Comment by akasolace** [comment] 2019-08-14 19:25
@DavidatorusF  I guess we should emphasizes it in the release notes.

**Comment by DavidatorusF** [comment] 2019-08-15 13:04
added
