### ISSUE TITLE
Exclude Last Lineup not working, when doing manual lineup

### ISSUE THREAD

**Issue by Sturzbach** [akasolace/HO#328] opened 2019-12-22 12:34 UTC
Hi,

it seems, that the option exclude last lineup is not working correctly, when filling the lineup manually. In the past also then doing manually, the players, which already played, where filtered out and not shown in the players choice list.
After may league match, i use it to setup my friendlies,m that every player gets his game in the week.

Can you please check and repair?

HO Version 2.000

**Comment by wsbrenk** [comment] 2019-12-22 14:23
i could reproduce this issue. i will try to find out the reason.

**Comment by wsbrenk** [comment] 2019-12-22 15:02
since Sep. 17th the previous lineup was not loaded anymore.

**Comment by akasolace** [comment] 2019-12-23 11:33
@wsbrenk for my info, previous lineup is really the previous one, or the last official game?

**Comment by akasolace** [comment] 2019-12-23 11:35
closed by db35c4bc82f08cd344e57d8c11aaf6e285e46354

**Closed** 2019-12-23 11:35 UTC
Labels: type: regression

**Comment by wsbrenk** [comment] 2019-12-23 11:43
> for my info, previous lineup is really the previous one, or the last official game?

it is the  "last lineup" mentioned in the hrf file
