### ISSUE TITLE
Error team download

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#735] opened 2020-10-19 19:37 UTC
The database was ok with manual adding folder in %appdata%.
Now two more problems cropped up (after changing to Beta r3266).
While attempting download for main team:
![HO-P1](https://user-images.githubusercontent.com/73033385/96500976-fa8a0e00-124f-11eb-83ed-4ac0c12d2203.jpg)
While attempting download for 2nd team:
![HO-P2](https://user-images.githubusercontent.com/73033385/96500997-007fef00-1250-11eb-8bed-d3036e933c7b.jpg)

_Originally posted by @KlausAH-Hattrick in https://github.com/akasolace/HO/issues/727#issuecomment-712386567_

**Comment by KlausAH-Hattrick** [comment] 2020-10-19 19:46
[HO.zip](https://github.com/akasolace/HO/files/5404316/HO.zip)

**Comment by wsbrenk** [comment] 2020-10-19 20:39
Database contains finished matches but no matchdetails (lineup infos) of them.

**Comment by akasolace** [comment] 2020-10-20 07:01
@wsbrenk If I understand correctly:
    1) when downloading data, calculation of training preview is made
    2) in his case match was finished but match details were not in the database and that throws an error

Now we still don't know why his database was not having match details.
I guess training preview only look for information from last played game, if this is correct can't we have something like:

```
if ( mlt == null ) {
                            mlt = download_match_details(.....)
                        }
```
@wsbrenk what do you think ?

**Comment by KlausAH-Hattrick** [comment] 2020-10-20 14:43
The downloading - first window - seems to complete, when I click on 'Save' then the errors come up as shown in the first two screenshots at top. Can I do sth to assist or help to resolve ?

**Comment by wsbrenk** [comment] 2020-10-20 17:09
@KlausAH-Hattrick gave us his logs [here](https://github.com/akasolace/HO/issues/727#issuecomment-711203590)

don't know why his connector logs problems while creating connection. if @KlausAH-Hattrick could give us the database of his first team we could try to debug.

@akasolace i think your idea to download match details could run into the same problems again

**Comment by KlausAH-Hattrick** [comment] 2020-10-20 18:26
I have now first UNinstalled HO4 completely, also deleting the db in %appdata% (after saving a backup on external drive).
Then fresh re-installed all from scratch, no problem, db directory 'HO' was created in %appdata%. I needed to authorise with HT again and after that I could also do the change as well as adding of team names in HO4 window (Database/User Administration).
After that, when "downloading" the same/similar error messages came up - see picture below.
Same with 2nd team, and in both cases opened HO4 as Administrator, all players were then shown on display in the window (however, after closing the mentioned error messages all time).
With the 3rd team I opened HO4 **NOT** as Administrator, I could **not** get the download to work at all.

![HO-P3](https://user-images.githubusercontent.com/73033385/96627942-dd1d7880-1311-11eb-94de-32b41247a1df.jpg)
[HO.zip](https://github.com/akasolace/HO/files/5410758/HO.zip)

Hope this info can help somewhere, the new db I have attached as well.
Any other assistance I can provide please let me know.

**Comment by wsbrenk** [comment] 2020-10-20 20:25
@KlausAH-Hattrick if i started HO4 with your db folder, i could not reproduce your download problems. for me it looks like a net configuration problem. i'm not an expert on this, but could it be, that you may be suffering from a firewall or something like this?

**Comment by wsbrenk** [comment] 2020-10-20 21:00
in his logs i found this:
Caused by: java.net.ConnectException: Connection timed out: connect

**Comment by akasolace** [comment] 2020-10-21 06:26
@wsbrenk @KlausAH-Hattrick  the issue with downloading was it a one-time issue or is it recurring? 

If it is recurring, do you have the same issue with a fresh install or only with the existing database?

**Comment by KlausAH-Hattrick** [comment] 2020-10-21 15:00
The problem still persists, even with the fresh installation. Also I need to launch as Administrator, else the App would not work. I do not use Antivirus which could cause this, and I also have disabled the Windows Firewall. No change, problem remains.
Getting really frusted now cos I cannot determine what's the problem or cause of it.
Any further good tips to try ?

**Comment by akasolace** [comment] 2020-10-21 16:53
are you using HO behind a proxy ?

**Comment by akasolace** [comment] 2020-10-21 16:55
@KlausAH-Hattrick 
so you always have the same error `Caused by: java.net.ConnectException: Connection timed out: connect` even on a fresh install ?  Have you been succesfully using HO in the past ? If yes, do you know when your issues started?  are you using HO behind a proxy ?

**Comment by KlausAH-Hattrick** [comment] 2020-10-22 18:12
All previous HO installations uninstalled, registry cleaned, fresh installation now of r3276. Firewall disabled, no proxy. Authorised 3 teams again with HT. Opened as Administrator. With 1st team only 2 error messages, after that all players and squad can be seen. 2nd team after 1st error comes NullpointerException and program closed, no players available. 3rd team lots of error messages but all players available, including squad, games and info on all other tabs.
I can't figure out why 3 teams have so much different behaviour. Screenshots below, db.zip added.
![HO-P4](https://user-images.githubusercontent.com/73033385/96912324-7bd8df00-14a2-11eb-8e3d-8ab3e21a474b.jpg)
[HO.zip](https://github.com/akasolace/HO/files/5424799/HO.zip)

I'm out of ideas now.

**Comment by akasolace** [comment] 2020-10-22 18:57
> Authorised 3 teams again with HT.

you had to do that because you started with fresh database ?

> I'm out of ideas now.

we will look into it. At the moment I am personnaly busy with other issues but this one is defintly on the list before next beta release ...

**Comment by wsbrenk** [comment] 2020-10-22 21:28
LastMatchDate=2021 is OK.

**Comment by KlausAH-Hattrick** [comment] 2020-10-22 21:54
Really appreciate your help. Wouldn't know what to do next to troubleshoot, as I'm not a programmer.
So have to trust your advice. Just tell me what to do next or what I can do to help finding out.

**Comment by KlausAH-Hattrick** [comment] 2020-10-26 16:39
Here some Logs from HO3 before.
[HO3 Logs.zip](https://github.com/akasolace/HO/files/5440114/HO3.Logs.zip)

**Comment by wsbrenk** [comment] 2020-10-26 18:15
Was August 28th the date when download didn't succeed the first time? This log is extemly short. Do you remember anything that could have changed then?

**Comment by akasolace** [comment] 2020-10-27 07:30
@wsbrenk have you try yourself with his DB? Are the downloads succesfull or do you have the same issue?

**Comment by KlausAH-Hattrick** [comment] 2020-10-27 14:27
[HO4-2710.zip](https://github.com/akasolace/HO/files/5445952/HO4-2710.zip)
Just tried again, now I get Nullpoint Exception with 1st team, the others download players but with several errors. Everytime things are different.

**Comment by wsbrenk** [comment] 2020-10-27 16:44
@akasolace @KlausAH-Hattrick could download match details without any problems 

data from october 22th:

![image](https://user-images.githubusercontent.com/11821502/97333636-1018bc80-187c-11eb-805d-771f0ef3ca03.png)

**Comment by KlausAH-Hattrick** [comment] 2020-10-27 20:39
Was there anything or any error in the datalogs that could point to a particular issue ?

**Comment by wsbrenk** [comment] 2020-10-27 21:38
@KlausAH-Hattrick the logs were clean. everything was working as expected.

**Comment by akasolace** [comment] 2020-10-27 22:35
@wsbrenk  so it means it is a connexion issue from @KlausAH-Hattrick side?

**Comment by KlausAH-Hattrick** [comment] 2020-10-28 06:43
If it works on your side sure the logs have no error. I mean was there was any error in the logs that could point to the problem in the db **when I sent/uploaded** - from the unsuccessful tries I had.

**Comment by akasolace** [comment] 2020-10-28 07:34
@KlausAH-Hattrick are you using HO on your personal or on a corporate pc?

**Comment by KlausAH-Hattrick** [comment] 2020-10-28 17:07
Using personal PC, no Firewall (have disabled Firewall and tried to run, same result with problems), no proxy, no antivirus programm (except for IO-Bit Malwarefighter). The program HT-History downloaded, installed, authorised and run - no problem. I can see all Tabs, means Players, Match Archive and Transfers. Absolutely problemfree and easy. Next ? .... :)

**Comment by akasolace** [comment] 2020-10-28 17:45
could you try to run HO! without IO-Bit Malwarefighter ?
also you told me you already tried with fresh install (i.e resetting the token) and you still had the issue, right ?

**Comment by akasolace** [comment] 2020-10-29 21:01
@KlausAH-Hattrick  also did you try with portable version ? Do you have the same result ?

**Comment by KlausAH-Hattrick** [comment] 2020-10-30 18:14
Disabled Windows Firewall, uninstalled IO-Bit Malware Fighter, uninstalled small programs of past two months, installed the HO4-Portable version - results are the same as before with permanent error messages.

**Comment by wsbrenk** [comment] 2020-10-30 19:00
@akasolace i remember that @KlausAH-Hattrick  is running Windows 8.1 (see his logs). could it be, that openjdk14.01 has problems with such an old windows version?

**Comment by akasolace** [comment] 2020-10-30 20:28
@KlausAH-Hattrick are you running the portable version with the embedded JDK ?

**Comment by KlausAH-Hattrick** [comment] 2020-10-30 20:48
That's the one I used for installation: HO-4.0.1.3266-portable-win-BETA-JRE

**Comment by akasolace** [comment] 2020-10-30 21:01
@KlausAH-Hattrick 

Just tried again, open your db and click download: I had no issue

![image](https://user-images.githubusercontent.com/1136496/97754979-ae18bb00-1af8-11eb-99a7-c069f56020e3.png)

we can't reproduce the bug so it is complicated to go further. As it works for me it means your token is valid, your db is not corrupted and HO! is working. It has to do with your system config but we can't tell what it is. Somewhere somehow your system is blocking HO! from accessing internet.

**Closed** 2020-11-13 08:02 UTC
Labels: reso: can't reproduce, reso: info needed, reso: won't fix
